<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class AddPracticeQuestions extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        {
            DB::table('practice')->insert([
                [
                    'course_id' => 1,
                    'section_id' => 1,
                    'question' => '_ all the candles on the birthday cake.',
                    'question_uk' => 'Задуй всі свічки на іменинному пирозі.',
                    'question_ru' => 'Задуй все свечи на именинном пироге.',
                    'answers' => '["blow out", "try out", "move out"]',
                    'correct_answer' => 'blow out',
                    'created_at' => now(),
                ],
                [
                    'course_id' => 1,
                    'section_id' => 1,
                    'question' => 'We could just _ in bed all day.',
                    'question_uk' => 'Ми могли просто валятися в ліжку весь день.',
                    'question_ru' => 'Мы могли просто лежать в постели весь день.',
                    'answers' => '["lie around", "move over", "lie down"]',
                    'correct_answer' => 'lie around',
                    'created_at' => now(),
                ],
                [
                    'course_id' => 1,
                    'section_id' => 1,
                    'question' => 'We want to _ now.',
                    'question_uk' => 'Ми хочемо переїхати зараз.',
                    'question_ru' => 'Мы хотим въехать сейчас.',
                    'answers' => '["move in", "try on", "lock up"]',
                    'correct_answer' => 'move in',
                    'created_at' => now(),
                ],
                [
                    'course_id' => 1,
                    'section_id' => 1,
                    'question' => 'I can’t wait to _ that plane.',
                    'question_uk' => 'Задуй всі свічки на іменинному пирозі.',
                    'question_ru' => 'Скоріше б сісти на цей літак.',
                    'answers' => '["get on", "turn up", "chill out"]',
                    'correct_answer' => 'get on',
                    'created_at' => now(),
                ],
                [
                    'course_id' => 1,
                    'section_id' => 1,
                    'question' => 'Not everyone can afford to _ in a hotel there.',
                    'question_uk' => 'Далеко не кожен може дозволити собі зупинку в готелі.',
                    'question_ru' => 'Далеко не каждый может позволить себе остановку в отеле.',
                    'answers' => '["stop over", "pass down", "turn over"]',
                    'correct_answer' => 'stop over',
                    'created_at' => now(),
                ],
                [
                    'course_id' => 1,
                    'section_id' => 1,
                    'question' => 'Always _ wherever you go.',
                    'question_uk' => 'Одягайся добре куди б ти не пішов.',
                    'question_ru' => 'Одевайся хорошо куда бы ты не пошел.',
                    'answers' => '["dress up", "feel up to", "roll up"]',
                    'correct_answer' => 'dress up',
                    'created_at' => now(),
                ],
                [
                    'course_id' => 1,
                    'section_id' => 1,
                    'question' => 'The rain continued to _.',
                    'question_uk' => 'Дощ продовжував лити.',
                    'question_ru' => 'Дождь продолжал лить.',
                    'answers' => '["pour down", "shoot off", "stop over"]',
                    'correct_answer' => 'pour down',
                    'created_at' => now(),
                ],
                [
                    'course_id' => 1,
                    'section_id' => 1,
                    'question' => 'I don’t _ fizzy drinks - I prefer water.',
                    'question_uk' => 'Я не люблю газовані напої - я віддаю перевагу воду.',
                    'question_ru' => 'Я не люблю газированные напитки - я предпочитаю воду.',
                    'answers' => '["care for", "hang out", "watch out for"]',
                    'correct_answer' => 'care for',
                    'created_at' => now(),
                ],
                [
                    'course_id' => 1,
                    'section_id' => 1,
                    'question' => 'I came to _ you _.',
                    'question_uk' => 'Я приїхав тебе підбадьорити.',
                    'question_ru' => 'Я приехала тебя подбодрить.',
                    'answers' => '["cheer up", "think up", "laze about"]',
                    'correct_answer' => 'cheer up',
                    'created_at' => now(),
                ],
                [
                    'course_id' => 1,
                    'section_id' => 1,
                    'question' => 'Stop _ – this is serious!',
                    'question_uk' => 'Перестань балуватися - це серйозно.',
                    'question_ru' => 'Перестань баловаться - это серьезно.',
                    'answers' => '["fool around", "get on", "brush up"]',
                    'correct_answer' => 'fool around',
                    'created_at' => now(),
                ],
                [
                    "course_id" => 1,
                    "section_id" => 2,
                    "question" => "She opened the door and let me _.",
                    "question_uk" => "Вона відкрила двері і впустила мене.",
                    "question_ru" => "Она открыла двери и впустила меня.",
                    "answers" => '["call in", "rub in", "in"]',
                    "correct_answer" => "in",
                    "created_at" => now(),
                ],
                [
                    "course_id" => 1,
                    "section_id" => 2,
                    "question" => "Don’t leave them on your desk and let them _.",
                    "question_uk" => "Не залишайте речі на столі і не дозволяйте їм накопичуватися.",
                    "question_ru" => "Не оставляйте вещи на столе и не позволяйте им скапливаться.",
                    "answers" => '["nod off", "double up", "pile up"]',
                    "correct_answer" => "pile up",
                    "created_at" => now(),
                ],
                [
                    "course_id" => 1,
                    "section_id" => 2,
                    "question" => "The shirt really _ his new tie.",
                    "question_uk" => "Сорочка дійсно підкреслювала його нову краватку.",
                    "question_ru" => "Сорочка действительно подчеркивала его новый галстук.",
                    "answers" => '["looked for", "reached out", "showed off"]',
                    "correct_answer" => "showed off",
                    "created_at" => now(),
                ],
                [
                    "course_id" => 1,
                    "section_id" => 2,
                    "question" => "My boots are _ at the seams.",
                    "question_uk" => "Мої черевики розходяться по швах.",
                    "question_ru" => "Мои ботинки расходятся по швам.",
                    "answers" => '["dropping by", "using up", "coming apart"]',
                    "correct_answer" => "coming apart",
                    "created_at" => now(),
                ],
                [
                    "course_id" => 1,
                    "section_id" => 2,
                    "question" => "When we arrived, her boyfriend _ drinks.",
                    "question_uk" => "Коли ми прийшли, її хлопець розливав напої.",
                    "question_ru" => "Когда мы пришли, ее парень разливал напитки.",
                    "answers" => '["lined up", "put aside", "poured out"]',
                    "correct_answer" => "poured out",
                    "created_at" => now(),
                ],
                [
                    "course_id" => 1,
                    "section_id" => 2,
                    "question" => "He _ his jacket.",
                    "question_uk" => "Він застебнув куртку.",
                    "question_ru" => "Он застегнул куртку.",
                    "answers" => '["fixed up", "paid for", "zipped up"]',
                    "correct_answer" => "zipped up",
                    "created_at" => now(),
                ],
                [
                    "course_id" => 1,
                    "section_id" => 2,
                    "question" => "They managed to _ 47 samples of different ages.",
                    "question_uk" => "Їм вдалося викопати 47 зразків різного віку.",
                    "question_ru" => "Им удалось откопать 47 образцов разного возраста.",
                    "answers" => '["double up", "throw out", "dig out"]',
                    "correct_answer" => "dig out",
                    "created_at" => now(),
                ],
                [
                    "course_id" => 1,
                    "section_id" => 2,
                    "question" => "After our busy day, we both sat and _ in front of the TV.",
                    "question_uk" => "Після напруженого дня ми обидва сіли і «відключилися» перед телевізором.",
                    "question_ru" => "После напряженного дня мы оба сели и «отключились» перед телевизором.",
                    "answers" => '["joined in", "turned down", "nodded off"]',
                    "correct_answer" => "nodded off",
                    "created_at" => now(),
                ],
                [
                    "course_id" => 1,
                    "section_id" => 2,
                    "question" => "I’m just starting to _ after taking the dogs out this morning.",
                    "question_uk" => "Я тільки починаю зігріватися після ранкової прогулянки з собаками.",
                    "question_ru" => "Я только начинаю согреваться после утренней прогулки с псами.",
                    "answers" => '["throw away", "come back", "throw out"]',
                    "correct_answer" => "throw out",
                    "created_at" => now(),
                ],
                [
                    "course_id" => 1,
                    "section_id" => 2,
                    "question" => "I _ the dust from my shoes every day.",
                    "question_uk" => "Я очищую пил з моїх черевиків кожен день.",
                    "question_ru" => "Я очищаю пыль с моих ботинок каждый день.",
                    "answers" => '["clean up", "rub in", "brush off"]',
                    "correct_answer" => "brush off",
                    "created_at" => now(),
                ],
                [
                    "course_id" => 1,
                    "section_id" => 3,
                    "question" => "I’d like to _ your friend Phoebe.",
                    "question_uk" => "Я б хотів запросити Фібі на побачення.",
                    "question_ru" => "Я бы хотел пригласить Фиби на свидание.",
                    "answers" => '["ask out", "get at", "take over"]',
                    "correct_answer" => "ask out",
                    "created_at" => now(),
                ],
                [
                    "course_id" => 1,
                    "section_id" => 3,
                    "question" => "He is too smart to _ that trick.",
                    "question_uk" => "Він занадто розумний, щоб повестися на цей трюк.",
                    "question_ru" => "Он слишком умный, чтобы вестись на этот трюк.",
                    "answers" => '["fall for", "get around", "go on"]',
                    "correct_answer" => "fall for",
                    "created_at" => now(),
                ],
                [
                    "course_id" => 1,
                    "section_id" => 3,
                    "question" => "I heard _ my cousin.",
                    "question_uk" => "Я отримав звістку від мого двоюрідного брата.",
                    "question_ru" => "Я получил известие от моего двоюродного брата.",
                    "answers" => '["from", "dropped around", "write up"]',
                    "correct_answer" => "from",
                    "created_at" => now(),
                ],
                [
                    "course_id" => 1,
                    "section_id" => 3,
                    "question" => "You can always _ Kate!",
                    "question_uk" => "Ти завжди можеш покластися на Кейт!",
                    "question_ru" => "Ты всегда можешь положиться на Кейт!",
                    "answers" => '["depend on", "keep off", "speak up"]',
                    "correct_answer" => "depend on",
                    "created_at" => now(),
                ],
                [
                    "course_id" => 1,
                    "section_id" => 3,
                    "question" => "She _ to a friend that she had lied to her mum.",
                    "question_uk" => "Вона розповіла другу секрет про те, що вона брехала мамі.",
                    "question_ru" => "Она рассказала другу секрет о том, что она врала маме.",
                    "answers" => '["let on", "dried up", "droned on"]',
                    "correct_answer" => "let on",
                    "created_at" => now(),
                ],
                [
                    "course_id" => 1,
                    "section_id" => 3,
                    "question" => "Pass the book _ to Michael, please.",
                    "question_uk" => "Передай книгу Майклу, будь ласка.",
                    "question_ru" => "Передай книгу Майклу, пожалуйста.",
                    "answers" => '["on", "leave aside", "open up"]',
                    "correct_answer" => "on",
                    "created_at" => now(),
                ],
                [
                    "course_id" => 1,
                    "section_id" => 3,
                    "question" => "I have to _ the confession out of him.",
                    "question_uk" => "Я повинна витягнути (вибити) з нього інформацію.",
                    "question_ru" => "Я должна вытянуть (выбить) из него информацию.",
                    "answers" => '["drag", "break in", "get through"]',
                    "correct_answer" => "drag",
                    "created_at" => now(),
                ],
                [
                    "course_id" => 1,
                    "section_id" => 3,
                    "question" => "I’m sorry to _ on your conversation.",
                    "question_uk" => "Вибачте, що вклинилася у вашу розмову.",
                    "question_ru" => "Извините, что вклинилась в ваш разговор.",
                    "answers" => '["break in", "engage in sb", "lead into"]',
                    "correct_answer" => "break in",
                    "created_at" => now(),
                ],
                [
                    "course_id" => 1,
                    "section_id" => 3,
                    "question" => "Open up your _ to him.",
                    "question_uk" => "Розкрий своє серце йому.",
                    "question_ru" => "Раскрой свое сердце ему.",
                    "answers" => '["heart", "mix with", "go along with"]',
                    "correct_answer" => "heart",
                    "created_at" => now(),
                ],
                [
                    "course_id" => 1,
                    "section_id" => 3,
                    "question" => "They just _ my complaints.",
                    "question_uk" => "Вони просто проігнорували мої скарги.",
                    "question_ru" => "Они просто проигнорировали мои жалобы.",
                    "answers" => '["brushed aside", "clam up", "take down"]',
                    "correct_answer" => "brushed aside",
                    "created_at" => now(),
                ],
                [
                    "course_id" => 1,
                    "section_id" => 4,
                    "question" => "How does your husband _ with his employees?",
                    "question_uk" => "Як твій чоловік ладить зі своїми співробітниками?",
                    "question_ru" => "Как твой муж ладит со своими сотрудниками?",
                    "answers" => '["bring along", "come along", "get along"]',
                    "correct_answer" => "get along",
                    "created_at" => now(),
                ],
                [
                    "course_id" => 1,
                    "section_id" => 4,
                    "question" => "What do you _ of him?",
                    "question_uk" => "Що ви про нього думаєте?",
                    "question_ru" => "Что вы о нем думаете?",
                    "answers" => '["make up", "turn to", "make of"]',
                    "correct_answer" => "make of",
                    "created_at" => now(),
                ],
                [
                    "course_id" => 1,
                    "section_id" => 4,
                    "question" => "I want to _.",
                    "question_uk" => "Я хочу наверстати все упущене.",
                    "question_ru" => "Я хочу наверстать все упущенное.",
                    "answers" => '["freeze sb out", "pay back", "catch up"]',
                    "correct_answer" => "catch up",
                    "created_at" => now(),
                ],
                [
                    "course_id" => 1,
                    "section_id" => 4,
                    "question" => "I don’t want to _.",
                    "question_uk" => "Я не хочу втручатися.",
                    "question_ru" => "Я не хочу вмешиваться.",
                    "answers" => '["pin down", "butter sb up", "butt in"]',
                    "correct_answer" => "butt in",
                    "created_at" => now(),
                ],
                [
                    "course_id" => 1,
                    "section_id" => 4,
                    "question" => "Why did this meeting _?",
                    "question_uk" => "Чому відбулася ця зустріч?",
                    "question_ru" => "Почему произошла эта встреча?",
                    "answers" => '["get together", "tell apart", "come about"]',
                    "correct_answer" => "come about",
                    "created_at" => now(),
                ],
                [
                    "course_id" => 1,
                    "section_id" => 4,
                    "question" => "Michael _ with Diana at the party yesterday.",
                    "question_uk" => "Майкл почав зустрічатися з Діаною вчора на вечірці.",
                    "question_ru" => "Майкл начал встречаться с Дианой вчера на вечеринке.",
                    "answers" => '["play at", "clear out", "paired off"]',
                    "correct_answer" => "paired off",
                    "created_at" => now(),
                ],
                [
                    "course_id" => 1,
                    "section_id" => 4,
                    "question" => "I think she’s trying to _ her up.",
                    "question_uk" => "Я думаю, вона намагається задобрити її.",
                    "question_ru" => "Я думаю она пытается задобрить ее.",
                    "answers" => '["finish with sb", "warm to sb", "butter"]',
                    "correct_answer" => "butter",
                    "created_at" => now(),
                ],
                [
                    "course_id" => 1,
                    "section_id" => 4,
                    "question" => "I always _ those two sisters up because they are twins.",
                    "question_uk" => "Я завжди плутаю цих двох сестер, тому що вони близнюки.",
                    "question_ru" => "Я всегда путаю этих двух сестер, потому что они близнецы.",
                    "answers" => '["make up", "bring up", "mix up"]',
                    "correct_answer" => "mix up",
                    "created_at" => now(),
                ],
                [
                    "course_id" => 1,
                    "section_id" => 4,
                    "question" => "Why did they _?",
                    "question_uk" => "Чому вони віддалилися один від одного?",
                    "question_ru" => "Почему они отдалились друг от друга?",
                    "answers" => '["cotton on", "stick up for", "grow apart"]',
                    "correct_answer" => "grow apart",
                    "created_at" => now(),
                ],
                [
                    "course_id" => 1,
                    "section_id" => 4,
                    "question" => "I think he’s _ on me.",
                    "question_uk" => "Мені здається, він мені зраджує.",
                    "question_ru" => "Мне кажется он мне изменяет.",
                    "answers" => '["hit it off", "fit in", "cheating"]',
                    "correct_answer" => "cheating",
                    "created_at" => now(),
                ],
                [
                    "course_id" => 1,
                    "section_id" => 5,
                    "question" => "The film _ us up considerably.",
                    "question_uk" => "Цей фільм нас дуже розвеселив.",
                    "question_ru" => "Этот фильм нас очень развеселил.",
                    "answers" => '["grew on sb", "lived for", "cheered"]',
                    "correct_answer" => "cheered",
                    "created_at" => now(),
                ],
                [
                    "course_id" => 1,
                    "section_id" => 5,
                    "question" => "I can’t _ over, that you loved me.",
                    "question_uk" => "Не можу повірити, що ти любила мене.",
                    "question_ru" => "Не могу поверить, что ты любила меня.",
                    "answers" => '["gross out", "snake up", "get"]',
                    "correct_answer" => "get",
                    "created_at" => now(),
                ],
                [
                    "course_id" => 1,
                    "section_id" => 5,
                    "question" => "He's looking _ to meeting her.",
                    "question_uk" => "Він з нетерпінням чекає зустрічі з нею.",
                    "question_ru" => "Он с нетерпением ждет встречи с ней.",
                    "answers" => '["sinking in", "ticking sb on", "forward"]',
                    "correct_answer" => "forward",
                    "created_at" => now(),
                ],
                [
                    "course_id" => 1,
                    "section_id" => 5,
                    "question" => "The kids got bored and started _ around.",
                    "question_uk" => "Дітям стало нудно, і вони почали шуміти.",
                    "question_ru" => "Детям стало скучном и они начали шуметь.",
                    "answers" => '["warming to", "bowling over", "monkeying"]',
                    "correct_answer" => "monkeying",
                    "created_at" => now(),
                ],
                [
                    "course_id" => 1,
                    "section_id" => 5,
                    "question" => "At first she didn’t like the idea, but she _ round.",
                    "question_uk" => "Спочатку їй ця ідея не сподобалася, але вона змінила свою думку.",
                    "question_ru" => "Сначала ей эта идея не поправилась , но она изменила свое мнение.",
                    "answers" => '["lighted up", "spilt (sth) out", "came"]',
                    "correct_answer" => "came",
                    "created_at" => now(),
                ],
                [
                    "course_id" => 1,
                    "section_id" => 5,
                    "question" => "They _ up when they heard what I had done.",
                    "question_uk" => "Вони раптово розсердилися, коли почули, що я зробив.",
                    "question_ru" => "Они внезапно рассердились, когда услышали, что я сделал.",
                    "answers" => '["cheered up", "chickened out", "blew"]',
                    "correct_answer" => "blew",
                    "created_at" => now(),
                ],
                [
                    "course_id" => 1,
                    "section_id" => 5,
                    "question" => "The beauty of music _ him away.",
                    "question_uk" => "Краса музики його захопила.",
                    "question_ru" => "Красота музыки его захватила.",
                    "answers" => '["bored into sb", "picked oneself up", "carried"]',
                    "correct_answer" => "carried",
                    "created_at" => now(),
                ],
                [
                    "course_id" => 1,
                    "section_id" => 5,
                    "question" => "I will not _ up.",
                    "question_uk" => "Я не збираюся здаватися.",
                    "question_ru" => "Я не собираюсь сдаваться.",
                    "answers" => '["cut up", "burn out", "give"]',
                    "correct_answer" => "give",
                    "created_at" => now(),
                ],
                [
                    "course_id" => 1,
                    "section_id" => 5,
                    "question" => "That song always _ me back to when I was at university.",
                    "question_uk" => "Ця пісня нагадує мені про мої студентські роки.",
                    "question_ru" => "Эта песня напоминает мне о моих студенческих годах.",
                    "answers" => '["keeps form", "passes for", "takes"]',
                    "correct_answer" => "takes",
                    "created_at" => now(),
                ],
                [
                    "course_id" => 1,
                    "section_id" => 5,
                    "question" => "We can't let bad memories _ away at us.",
                    "question_uk" => "Ми не можемо дозволити поганим спогадам з'їдати нас (зсередини).",
                    "question_ru" => "Мы не можем позволить плохим воспоминаниям съедать нас (изнутри).",
                    "answers" => '["flood back", "tense up", "eat"]',
                    "correct_answer" => "eat",
                    "created_at" => now(),
                ],
                [
                    "course_id" => 1,
                    "section_id" => 6,
                    "question" => "The space shuttle will _ off at 9 a.m.",
                    "question_uk" => "Космічний корабель злетить о 9 ранку.",
                    "question_ru" => "Космический корабль взлетит в 9 утра.",
                    "answers" => '["take off", "see off", "lift"]',
                    "correct_answer" => "lift",
                    "created_at" => now(),
                ],
                [
                    "course_id" => 1,
                    "section_id" => 6,
                    "question" => "We were completely _ off from the busy modern world there.",
                    "question_uk" => "Там ми були повністю відрізані від світу.",
                    "question_ru" => "Там мы были полностью отрезаны от мира.",
                    "answers" => '["got to", "packed away", "cut"]',
                    "correct_answer" => "cut",
                    "created_at" => now(),
                ],
                [
                    "course_id" => 1,
                    "section_id" => 6,
                    "question" => "I have to _ in and get to work.",
                    "question_uk" => "Я повинна зареєструватися і приступити до роботи.",
                    "question_ru" => "Я должна зарегистрироваться и приступить к работе.",
                    "answers" => '["get into", "eat out", "check"]',
                    "correct_answer" => "check",
                    "created_at" => now(),
                ],
                [
                    "course_id" => 1,
                    "section_id" => 6,
                    "question" => "I've been _ up on Japan as I'm going to live there next year.",
                    "question_uk" => "Я вичитую інформацію про Японію, оскільки збираюся там жити наступного року.",
                    "question_ru" => "Я вычитываю информацию о Японии, поскольку собираюсь там жить в следующем году.",
                    "answers" => '["making out sth", "popping in", "reading"]',
                    "correct_answer" => "reading",
                    "created_at" => now(),
                ],
                [
                    "course_id" => 1,
                    "section_id" => 6,
                    "question" => "When does our train _ in?",
                    "question_uk" => "Коли прибуває наш поїзд?",
                    "question_ru" => "Когда прибывает наш поезд?",
                    "answers" => '["take off", "hop off", "get"]',
                    "correct_answer" => "get",
                    "created_at" => now(),
                ],
                [
                    "course_id" => 1,
                    "section_id" => 6,
                    "question" => "We have 15 min until our bus, let's _ into the café and order take away coffee?",
                    "question_uk" => "У нас 15 хв до автобуса, давай заскочимо в кафе і візьмемо каву з собою.",
                    "question_ru" => "У нас 15 мин до автобуса давай заскочим в кафе и возьмём кофе с собой.",
                    "answers" => '["get to", "chill out", "pop"]',
                    "correct_answer" => "pop",
                    "created_at" => now(),
                ],
                [
                    "course_id" => 1,
                    "section_id" => 6,
                    "question" => "Hurry up, or we'll _ the train.",
                    "question_uk" => "Поспішай, інакше ми запізнимося на поїзд.",
                    "question_ru" => "Поторопись, иначе мы опоздаем на поезд.",
                    "answers" => '["lift off", "stop off", "miss"]',
                    "correct_answer" => "miss",
                    "created_at" => now(),
                ],
                [
                    "course_id" => 1,
                    "section_id" => 6,
                    "question" => "I’d like to travel more, but my salary _ me down.",
                    "question_uk" => "Я б хотіла більше подорожувати, але моя зарплата мене обмежує.",
                    "question_ru" => "Я бы хотела больше путешествовать но моя зарплата меня ограничивает.",
                    "answers" => '["brushes up", "tends towards", "ties"]',
                    "correct_answer" => "ties",
                    "created_at" => now(),
                ],
                [
                    "course_id" => 1,
                    "section_id" => 6,
                    "question" => "The boys _ away their tents.",
                    "question_uk" => "Хлопці упакували свої намети.",
                    "question_ru" => "Мальчики упаковали свои палатки.",
                    "answers" => '["tore off", "winded down", "packed"]',
                    "correct_answer" => "packed",
                    "created_at" => now(),
                ],
                [
                    "course_id" => 1,
                    "section_id" => 6,
                    "question" => "They _ out that he had visited Berlin.",
                    "question_uk" => "Вони вигадали, що він був у Берліні.",
                    "question_ru" => "Они выдумали что был в Берлине.",
                    "answers" => '["hurried up", "showed sb around", "made"]',
                    "correct_answer" => "made",
                    "created_at" => now(),
                ],
                [
                    "course_id" => 1,
                    "section_id" => 7,
                    "question" => "I think, I'm _ with the flu.",
                    "question_uk" => "Здається, я підхопив грип.",
                    "question_ru" => "Кажется я подхватил грипп.",
                    "answers" => '["staying up", "fighting off", "coming down"]',
                    "correct_answer" => "coming down",
                    "created_at" => now(),
                ],
                [
                    "course_id" => 1,
                    "section_id" => 7,
                    "question" => "She _ and hurt her knee badly.",
                    "question_uk" => "Вона впала і сильно вдарила коліно.",
                    "question_ru" => "Она упала и сильно ударила колено.",
                    "answers" => '["flipped out", "pulled through", "fell over"]',
                    "correct_answer" => "fell over",
                    "created_at" => now(),
                ],
                [
                    "course_id" => 1,
                    "section_id" => 7,
                    "question" => "I'm just happy I'm _ it down.",
                    "question_uk" => "Я радий, що хоча б стримав рвоту.",
                    "question_ru" => "Я рад, что хотя бы сдержал рвоту.",
                    "answers" => '["passing out", "keeping away", "keeping"]',
                    "correct_answer" => "keeping",
                    "created_at" => now(),
                ],
                [
                    "course_id" => 1,
                    "section_id" => 7,
                    "question" => "I was hit on the head and _.",
                    "question_uk" => "Мене вдарили по голові, і я втратив свідомість.",
                    "question_ru" => "Меня ударили по голове, и я потерял сознание.",
                    "answers" => '["ate away", "brought around", "passed out"]',
                    "correct_answer" => "passed out",
                    "created_at" => now(),
                ],
                [
                    "course_id" => 1,
                    "section_id" => 7,
                    "question" => "I've been trying to _ a meeting with my doctor for a week now.",
                    "question_uk" => "Я вже тиждень намагаюся домовитися про зустріч з лікарем.",
                    "question_ru" => "Я уже неделю пытаюсь договориться о встрече с доктором.",
                    "answers" => '["make out", "wear sb out", "fix up"]',
                    "correct_answer" => "fix up",
                    "created_at" => now(),
                ],
                [
                    "course_id" => 1,
                    "section_id" => 7,
                    "question" => "We always do exercises to _ before playing tennis.",
                    "question_uk" => "Ми завжди розминаємося перед грою в теніс.",
                    "question_ru" => "Мы всегда разминаемся перед игрой в теннис.",
                    "answers" => '["phase sth out", "frown on", "loosen up"]',
                    "correct_answer" => "loosen up",
                    "created_at" => now(),
                ],
                [
                    "course_id" => 1,
                    "section_id" => 7,
                    "question" => "Half of Martha's class has _ with flu.",
                    "question_uk" => "Половина класу Марти захворіла на грип.",
                    "question_ru" => "Половина класса Марты заболела гриппом.",
                    "answers" => '["asked after", "dozed off", "gone down"]',
                    "correct_answer" => "gone down",
                    "created_at" => now(),
                ],
                [
                    "course_id" => 1,
                    "section_id" => 7,
                    "question" => "When I _ , I want to become a rock star.",
                    "question_uk" => "Коли я виросту, я хочу стати рок-зіркою.",
                    "question_ru" => "Когда я вырасту, я хочу стать рок-звездой.",
                    "answers" => '["build oneself up", "pull through", "grow up"]',
                    "correct_answer" => "grow up",
                    "created_at" => now(),
                ],
                [
                    "course_id" => 1,
                    "section_id" => 7,
                    "question" => "Hey, quit _! This is the best part of the film.",
                    "question_uk" => "Гей, перестань дрімати! Це найкраща частина фільму.",
                    "question_ru" => "Эй, хватит дремать! Это лучшая часть фильма.",
                    "answers" => '["bringing around", "getting up", "dozing off"]',
                    "correct_answer" => "dozing off",
                    "created_at" => now(),
                ],
                [
                    "course_id" => 1,
                    "section_id" => 7,
                    "question" => "Medicines should always be _ from children.",
                    "question_uk" => "Ліки завжди слід тримати подалі від дітей.",
                    "question_ru" => "Лекарства всегда следует держать подальше от детей.",
                    "answers" => '["stepped aside", "drank up", "kept away"]',
                    "correct_answer" => "kept away",
                    "created_at" => now(),
                ],
                [
                    "course_id" => 1,
                    "section_id" => 8,
                    "question" => "In other words, it could _.",
                    "question_uk" => "Іншими словами, це може закінчитися.",
                    "question_ru" => "Проще говоря, он может закончиться.",
                    "answers" => '["die out", "blow down", "run out"]',
                    "correct_answer" => "run out",
                    "created_at" => now(),
                ],
                [
                    "course_id" => 1,
                    "section_id" => 8,
                    "question" => "A lot of fences _ in the hurricane last night.",
                    "question_uk" => "Учорашній ураган зніс багато огорож.",
                    "question_ru" => "Вчерашний ураган снёс много ограждений.",
                    "answers" => '["drew back", "stayed away from", "blew down"]',
                    "correct_answer" => "blew down",
                    "created_at" => now(),
                ],
                [
                    "course_id" => 1,
                    "section_id" => 8,
                    "question" => "We _ the main road.",
                    "question_uk" => "Ми звернули з головної дороги.",
                    "question_ru" => "Мы свернули с главной дороги.",
                    "answers" => '["squashed up", "hung back", "turned off"]',
                    "correct_answer" => "turned off",
                    "created_at" => now(),
                ],
                [
                    "course_id" => 1,
                    "section_id" => 8,
                    "question" => "I wasn't sure how things would _ at first.",
                    "question_uk" => "Спочатку я не була впевнена, як все складеться.",
                    "question_ru" => "Сначала я была неуверенна, как всё сложиться.",
                    "answers" => '["hold over", "play along", "pan out"]',
                    "correct_answer" => "pan out",
                    "created_at" => now(),
                ],
                [
                    "course_id" => 1,
                    "section_id" => 8,
                    "question" => "The DVD player was _ and eventually broke down.",
                    "question_uk" => "DVD глючив, а потім зламався.",
                    "question_ru" => "DVD глючил, а потом сломался.",
                    "answers" => '["banging into", "bearing out", "playing up"]',
                    "correct_answer" => "playing up",
                    "created_at" => now(),
                ],
                [
                    "course_id" => 1,
                    "section_id" => 8,
                    "question" => "The robber was caught when someone _ the police.",
                    "question_uk" => "Грабіжника спіймали, коли хтось попередив поліцію.",
                    "question_ru" => "Грабителя поймали, когда кто-то предупредил полицию.",
                    "answers" => '["doomed to", "drew back", "tipped off"]',
                    "correct_answer" => "tipped off",
                    "created_at" => now(),
                ],
                [
                    "course_id" => 1,
                    "section_id" => 8,
                    "question" => "I heard someone _ my name from a distance.",
                    "question_uk" => "Я почув, як хтось здалеку викрикнув моє ім'я.",
                    "question_ru" => "Я услышал, как кто-то издалека выкрикнул мое имя.",
                    "answers" => '["zipping along", "occurring to", "calling out"]',
                    "correct_answer" => "calling out",
                    "created_at" => now(),
                ],
                [
                    "course_id" => 1,
                    "section_id" => 8,
                    "question" => "Grandma had to have surgery because her knees _.",
                    "question_uk" => "Бабусі довелося робити операцію, тому що її стан погіршився.",
                    "question_ru" => "Бабушке пришлось оперировать, потому что состояние её ухудшилось.",
                    "answers" => '["swung around", "made into", "gave out"]',
                    "correct_answer" => "gave out",
                    "created_at" => now(),
                ],
                [
                    "course_id" => 1,
                    "section_id" => 8,
                    "question" => "I'm tired - I've been _ all morning.",
                    "question_uk" => "Я втомився - я був зайнятий весь ранок.",
                    "question_ru" => "Я устал, я был занят всё утро.",
                    "answers" => '["going beyond", "calling off", "running around"]',
                    "correct_answer" => "running around",
                    "created_at" => now(),
                ],
                [
                    "course_id" => 1,
                    "section_id" => 8,
                    "question" => "I _ to meet the love of my life.",
                    "question_uk" => "Мені пощастило зустріти любов свого життя.",
                    "question_ru" => "Мне посчастливилось встретить любовь своей жизни.",
                    "answers" => '["headed off", "running across", "lucked out"]',
                    "correct_answer" => "lucked out",
                    "created_at" => now(),
                ],
                [
                    "course_id" => 1,
                    "section_id" => 9,
                    "question" => "She _ her mistakes and wrote the correct answers above them.",
                    "question_uk" => "Вона закреслила свої помилки і написала правильні відповіді над ними.",
                    "question_ru" => "Она перечеркнула свои ошибки и написала сверху правильные ответы.",
                    "answers" => '["zoned out", "brought up", "crossed out"]',
                    "correct_answer" => "crossed out",
                    "created_at" => now(),
                ],
                [
                    "course_id" => 1,
                    "section_id" => 9,
                    "question" => "I'm just _ what you've written.",
                    "question_uk" => "Я просто переглядаю те, що ви написали.",
                    "question_ru" => "Я всего лишь быстро просматриваю то, что вы написали.",
                    "answers" => '["passing around", "narrowing down", "looking over"]',
                    "correct_answer" => "looking over",
                    "created_at" => now(),
                ],
                [
                    "course_id" => 1,
                    "section_id" => 9,
                    "question" => "I totally _ the chemistry exam.",
                    "question_uk" => "Я повністю провалив тест з хімії.",
                    "question_ru" => "Я полностью провалил тест по химии.",
                    "answers" => '["plugged away", "rounded off", "screwed up"]',
                    "correct_answer" => "screwed up",
                    "created_at" => now(),
                ],
                [
                    "course_id" => 1,
                    "section_id" => 9,
                    "question" => "I _ on the last question.",
                    "question_uk" => "Я зробив помилку в останньому питанні.",
                    "question_ru" => "Я сделал ошибку в последним вопросе.",
                    "answers" => '["worked at", "tripped up", "tripped up"]',
                    "correct_answer" => "tripped up",
                    "created_at" => now(),
                ],
                [
                    "course_id" => 1,
                    "section_id" => 9,
                    "question" => "She successfully _ her exams.",
                    "question_uk" => "Вона успішно склала іспити.",
                    "question_ru" => "Она успешно сдала экзамены.",
                    "answers" => '["polished up", "gave back", "got through"]',
                    "correct_answer" => "got through",
                    "created_at" => now(),
                ],
                [
                    "course_id" => 1,
                    "section_id" => 9,
                    "question" => "I know you were trying to _ this morning.",
                    "question_uk" => "Я знаю, ти намагався вислизнути цього ранку.",
                    "question_ru" => "Я знаю, ты пытался ускользнуть утром.",
                    "answers" => '["drop out", "rub up on", "sneak out"]',
                    "correct_answer" => "sneak out",
                    "created_at" => now(),
                ],
                [
                    "course_id" => 1,
                    "section_id" => 9,
                    "question" => "She _ during the lecture because it was so boring.",
                    "question_uk" => "Вона відключилася під час лекції, бо було дуже нудно.",
                    "question_ru" => "Она не концентрировалась на лекции потому что она была скучной.",
                    "answers" => '["read out", "piped down", "zoned out"]',
                    "correct_answer" => "zoned out",
                    "created_at" => now(),
                ],
                [
                    "course_id" => 1,
                    "section_id" => 9,
                    "question" => "Concentrate on _ your best skills.",
                    "question_uk" => "Зосередься на вдосконаленні своїх найкращих навичок.",
                    "question_ru" => "Сфокусируйся на улучшении своих лучших навыков.",
                    "answers" => '["putting together", "sneaking out", "polishing up"]',
                    "correct_answer" => "polishing up",
                    "created_at" => now(),
                ],
                [
                    "course_id" => 1,
                    "section_id" => 9,
                    "question" => "You managed to _ the presentation quite well.",
                    "question_uk" => "Вам дуже непогано вдалося провести презентацію.",
                    "question_ru" => "Вам очень неплохо удалось провести презентацию.",
                    "answers" => '["leap out at", "take in", "carry off"]',
                    "correct_answer" => "carry off",
                    "created_at" => now(),
                ],
                [
                    "course_id" => 1,
                    "section_id" => 9,
                    "question" => "The teacher _ the handout.",
                    "question_uk" => "Учитель роздав роздруківки.",
                    "question_ru" => "Учитель раздал распечатки.",
                    "answers" => '["set up", "looked up", "passed out"]',
                    "correct_answer" => "passed out",
                    "created_at" => now(),
                ],
                [
                    "course_id" => 1,
                    "section_id" => 10,
                    "question" => "Why did electronic gadgets _ so fast?",
                    "question_uk" => "Чому електронні пристрої так швидко стали популярними?",
                    "question_ru" => "Почему электронные устройства так быстро стали популярными?",
                    "answers" => '["fall behind", "hurry up", "catch on"]',
                    "correct_answer" => "catch on",
                    "created_at" => now(),
                ],
                [
                    "course_id" => 1,
                    "section_id" => 10,
                    "question" => "The runner _ his teammates.",
                    "question_uk" => "Бігун відставав від своїх товаришів по команді.",
                    "question_ru" => "Бегун отставал от своих товарищей по команде.",
                    "answers" => '["got around to", "went through", "fell behind"]',
                    "correct_answer" => "fell behind",
                    "created_at" => now(),
                ],
                [
                    "course_id" => 1,
                    "section_id" => 10,
                    "question" => "She's _ for a new bike.",
                    "question_uk" => "Вона відкладає гроші на новий велосипед.",
                    "question_ru" => "Она откладывала деньги на новый велосипед.",
                    "answers" => '["loosing out", "turning into", "saving up"]',
                    "correct_answer" => "saving up",
                    "created_at" => now(),
                ],
                [
                    "course_id" => 1,
                    "section_id" => 10,
                    "question" => "They _ working after dark.",
                    "question_uk" => "Вони продовжували працювати після настання темряви.",
                    "question_ru" => "Они продолжали работать когда стемнело.",
                    "answers" => '["saved up", "came across", "kept on"]',
                    "correct_answer" => "kept on",
                    "created_at" => now(),
                ],
                [
                    "course_id" => 1,
                    "section_id" => 10,
                    "question" => "He _ the new knowledge.",
                    "question_uk" => "Він жадібно поглинав нові знання.",
                    "question_ru" => "Он жадно поглощал новые знания.",
                    "answers" => '["kept on", "kept up with", "ate up"]',
                    "correct_answer" => "ate up",
                    "created_at" => now(),
                ],
                [
                    "course_id" => 1,
                    "section_id" => 10,
                    "question" => "The idea sounded interesting and I decided to _ it up.",
                    "question_uk" => "Ідея здавалася цікавою, і я вирішив дізнатися про неї більше.",
                    "question_ru" => "Идея звучала интересно, и я решила узнать о ней больше.",
                    "answers" => '["spread out", "ate up", "follow"]',
                    "correct_answer" => "follow",
                    "created_at" => now(),
                ],
                [
                    "course_id" => 1,
                    "section_id" => 10,
                    "question" => "This is the message that we want to _ to the public.",
                    "question_uk" => "Це повідомлення, яке ми хочемо донести до громадськості.",
                    "question_ru" => "Это то сообщение, которое мы хотим донести до общественности.",
                    "answers" => '["think up", "come up with", "get across"]',
                    "correct_answer" => "get across",
                    "created_at" => now(),
                ],
                [
                    "course_id" => 1,
                    "section_id" => 10,
                    "question" => "She finally _ to painting the bedroom.",
                    "question_uk" => "Вона нарешті взялася за фарбування спальні.",
                    "question_ru" => "Она, наконец, смогла покрасить спальню.",
                    "answers" => '["got into", "got across", "got around"]',
                    "correct_answer" => "got around",
                    "created_at" => now(),
                ],
                [
                    "course_id" => 1,
                    "section_id" => 10,
                    "question" => "I was sick last week, that's why I _ on the chance at a new job.",
                    "question_uk" => "Я хворіла минулого тижня, тому втратила шанс на нову роботу.",
                    "question_ru" => "Я болела на прошлой неделе, поэтому потеряла шанс на новую работу.",
                    "answers" => '["caught on", "settled into", "lost out"]',
                    "correct_answer" => "lost out",
                    "created_at" => now(),
                ],
                [
                    "course_id" => 1,
                    "section_id" => 10,
                    "question" => "It is rather a difficult issue and we decided not to _ with its solution.",
                    "question_uk" => "Це досить складне питання, і ми вирішили не поспішати з його вирішенням.",
                    "question_ru" => "Это достаточно сложный вопрос и мы решили не торопиться с его решением.",
                    "answers" => '["save up", "follow up", "hurry up"]',
                    "correct_answer" => "hurry up",
                    "created_at" => now(),
                ],
                [
                    "course_id" => 1,
                    "section_id" => 11,
                    "question" => "We _ the car up and changed the tyre.",
                    "question_uk" => "Ми підняли автомобіль (на домкраті) і замінили шини.",
                    "question_ru" => "Мы подняли автомобиль (на домкрате) и заменили шины.",
                    "answers" => '["came by", "fell through", "jacked"]',
                    "correct_answer" => "jacked",
                    "created_at" => now(),
                ],
                [
                    "course_id" => 1,
                    "section_id" => 11,
                    "question" => "The nurse _ me down in a chair.",
                    "question_uk" => "Медсестра посадила мене на стул.",
                    "question_ru" => "Медсестра посадила меня на стул.",
                    "answers" => '["counted out", "stood up", "sat"]',
                    "correct_answer" => "sat",
                    "created_at" => now(),
                ],
                [
                    "course_id" => 1,
                    "section_id" => 11,
                    "question" => "As he got older, he started to _ up a little.",
                    "question_uk" => "З віком він почав трохи знижувати навантаження.",
                    "question_ru" => "С возрастом он начал немного снижать нагрузку.",
                    "answers" => '["see out", "take on", "ease"]',
                    "correct_answer" => "ease",
                    "created_at" => now(),
                ],
                [
                    "course_id" => 1,
                    "section_id" => 11,
                    "question" => "I was only _ out orders.",
                    "question_uk" => "Я всього лише виконував накази.",
                    "question_ru" => "Я всего лишь исполнял приказания.",
                    "answers" => '["working on", "selling out", "carrying"]',
                    "correct_answer" => "carrying",
                    "created_at" => now(),
                ],
                [
                    "course_id" => 1,
                    "section_id" => 11,
                    "question" => "They tried to _ us down on the price.",
                    "question_uk" => "Вони намагалися торгуватися щодо ціни.",
                    "question_ru" => "Они пытались торговаться насчет цены.",
                    "answers" => '["go about", "get ahead", "beat"]',
                    "correct_answer" => "beat",
                    "created_at" => now(),
                ],
                [
                    "course_id" => 1,
                    "section_id" => 11,
                    "question" => "I was immediately _ aside by the manager.",
                    "question_uk" => "Менеджер одразу покликав мене на приватну розмову.",
                    "question_ru" => "Менеджер сразу позвал меня на частный разговор.",
                    "answers" => '["factored in", "got in", "taken"]',
                    "correct_answer" => "taken",
                    "created_at" => now(),
                ],
                [
                    "course_id" => 1,
                    "section_id" => 11,
                    "question" => "She said that her husband _ in marketing.",
                    "question_uk" => "Вона сказала, що її чоловік працює в сфері маркетингу.",
                    "question_ru" => "Она сказала, что её муж работает в сфере маркетинга.",
                    "answers" => '["carries on with", "sees out", "works"]',
                    "correct_answer" => "works",
                    "created_at" => now(),
                ],
                [
                    "course_id" => 1,
                    "section_id" => 11,
                    "question" => "Try not to get too _ down in the details.",
                    "question_uk" => "Постарайся не сильно зациклюватися на деталях.",
                    "question_ru" => "Постарайся не сильно зацикливаться на деталях.",
                    "answers" => '["take on", "move along", "bogged"]',
                    "correct_answer" => "bogged",
                    "created_at" => now(),
                ],
                [
                    "course_id" => 1,
                    "section_id" => 11,
                    "question" => "I would rather _ on several small projects.",
                    "question_uk" => "Я, вважаю за краще працювати над кількома проектами.",
                    "question_ru" => "Я, предпочитаю работать над несколькими проектами.",
                    "answers" => '["spin out", "send off", "work"]',
                    "correct_answer" => "work",
                    "created_at" => now(),
                ],
                [
                    "course_id" => 1,
                    "section_id" => 11,
                    "question" => "I'm _ for the weekend - this week has been so hard.",
                    "question_uk" => "Я дуже сильно хочу (чекаю) вихідних, ця неділя була дуже важкою.",
                    "question_ru" => "Я очень сильно хочу (жду) выходных, эта неделя была очень тяжелой.",
                    "answers" => '["holding on", "doing over", "dying"]',
                    "correct_answer" => "dying",
                    "created_at" => now(),
                ],
                [
                    "course_id" => 1,
                    "section_id" => 11,
                    "question" => "We _ the car up and changed the tyre.",
                    "question_uk" => "Ми підняли автомобіль (на домкраті) і замінили шини.",
                    "question_ru" => "Мы подняли автомобиль (на домкрате) и заменили шины.",
                    "answers" => '["came by", "fell through", "jacked"]',
                    "correct_answer" => "jacked",
                    "created_at" => now(),
                ],
                [
                    "course_id" => 1,
                    "section_id" => 11,
                    "question" => "The nurse _ me down in a chair.",
                    "question_uk" => "Медсестра посадила мене на стул.",
                    "question_ru" => "Медсестра посадила меня на стул.",
                    "answers" => '["counted out", "stood up", "sat"]',
                    "correct_answer" => "sat",
                    "created_at" => now(),
                ],
                [
                    "course_id" => 1,
                    "section_id" => 11,
                    "question" => "As he got older, he started to _ up a little.",
                    "question_uk" => "З віком він почав трохи знижувати навантаження.",
                    "question_ru" => "С возрастом он начал немного снижать нагрузку.",
                    "answers" => '["see out", "take on", "ease"]',
                    "correct_answer" => "ease",
                    "created_at" => now(),
                ],
                [
                    "course_id" => 1,
                    "section_id" => 11,
                    "question" => "I was only _ out orders.",
                    "question_uk" => "Я всього лише виконував накази.",
                    "question_ru" => "Я всего лишь исполнял приказания.",
                    "answers" => '["working on", "selling out", "carrying"]',
                    "correct_answer" => "carrying",
                    "created_at" => now(),
                ],
                [
                    "course_id" => 1,
                    "section_id" => 11,
                    "question" => "They tried to _ us down on the price.",
                    "question_uk" => "Вони намагалися торгуватися щодо ціни.",
                    "question_ru" => "Они пытались торговаться насчет цены.",
                    "answers" => '["go about", "get ahead", "beat"]',
                    "correct_answer" => "beat",
                    "created_at" => now(),
                ],
                [
                    "course_id" => 1,
                    "section_id" => 11,
                    "question" => "I was immediately _ aside by the manager.",
                    "question_uk" => "Менеджер одразу покликав мене на приватну розмову.",
                    "question_ru" => "Менеджер сразу позвал меня на частный разговор.",
                    "answers" => '["factored in", "got in", "taken"]',
                    "correct_answer" => "taken",
                    "created_at" => now(),
                ],
                [
                    "course_id" => 1,
                    "section_id" => 11,
                    "question" => "She said that her husband _ in marketing.",
                    "question_uk" => "Вона сказала, що її чоловік працює в сфері маркетингу.",
                    "question_ru" => "Она сказала, что её муж работает в сфере маркетинга.",
                    "answers" => '["carries on with", "sees out", "works"]',
                    "correct_answer" => "works",
                    "created_at" => now(),
                ],
                [
                    "course_id" => 1,
                    "section_id" => 11,
                    "question" => "Try not to get too _ down in the details.",
                    "question_uk" => "Постарайся не сильно зациклюватися на деталях.",
                    "question_ru" => "Постарайся не сильно зацикливаться на деталях.",
                    "answers" => '["take on", "move along", "bogged"]',
                    "correct_answer" => "bogged",
                    "created_at" => now(),
                ],
                [
                    "course_id" => 1,
                    "section_id" => 11,
                    "question" => "I would rather _ on several small projects.",
                    "question_uk" => "Я, вважаю за краще працювати над кількома проектами.",
                    "question_ru" => "Я, предпочитаю работать над несколькими проектами.",
                    "answers" => '["spin out", "send off", "work"]',
                    "correct_answer" => "work",
                    "created_at" => now(),
                ],
                [
                    "course_id" => 1,
                    "section_id" => 11,
                    "question" => "I'm _ for the weekend - this week has been so hard.",
                    "question_uk" => "Я дуже сильно хочу (чекаю) вихідних, ця неділя була дуже важкою.",
                    "question_ru" => "Я очень сильно хочу (жду) выходных, эта неделя была очень тяжелой.",
                    "answers" => '["holding on", "doing over", "dying"]',
                    "correct_answer" => "dying",
                    "created_at" => now(),
                ],
                [
                    "course_id" => 1,
                    "section_id" => 12,
                    "question" => "For my nineteenth birthday, my friends _ together and bought me a watch.",
                    "question_uk" => "До мого 19-річчя мої друзі скинулися і купили мені годинник.",
                    "question_ru" => "К моему 19-летию мои друзья сбросились и купили мне часы.",
                    "answers" => '["matched up", "gathered up", "clubbed"]',
                    "correct_answer" => "clubbed",
                    "created_at" => now(),
                ],
                [
                    "course_id" => 1,
                    "section_id" => 12,
                    "question" => "They _ the pros and cons up carefully.",
                    "question_uk" => "Перед тим як прийняти рішення, вони ретельно зважили плюси і мінуси.",
                    "question_ru" => "Перед тем как принять решение, они тщательно взвесили плюсы и минусы.",
                    "answers" => '["sized up", "headed for", "weighed"]',
                    "correct_answer" => "weighed",
                    "created_at" => now(),
                ],
                [
                    "course_id" => 1,
                    "section_id" => 12,
                    "question" => "The UK _ with the death penalty in 1965.",
                    "question_uk" => "У 1965 р. Сполучене Королівство скасувало смертну кару.",
                    "question_ru" => "В 1965 г. Соединенные Королевство отменило смертную казнь.",
                    "answers" => '["allowed for", "blended in", "did away"]',
                    "correct_answer" => "did away",
                    "created_at" => now(),
                ],
                [
                    "course_id" => 1,
                    "section_id" => 12,
                    "question" => "You have to learn to _ above negative criticism.",
                    "question_uk" => "Тобі потрібно навчитися не звертати увагу на негативну критику.",
                    "question_ru" => "Тебе нужно научиться не обращать внимание на негативную критику.",
                    "answers" => '["talk into", "throw out", "rise"]',
                    "correct_answer" => "rise",
                    "created_at" => now(),
                ],
                [
                    "course_id" => 1,
                    "section_id" => 12,
                    "question" => "The proposal to build a new road was _ down.",
                    "question_uk" => "Пропозиція про будівництво нової дороги була відхилена.",
                    "question_ru" => "Предложение о строительстве новой дороги было отклонено.",
                    "answers" => '["spaced out", "came round to", "voted"]',
                    "correct_answer" => "voted",
                    "created_at" => now(),
                ],
                [
                    "course_id" => 1,
                    "section_id" => 12,
                    "question" => "She didn't want to let me go, but I finally managed to _ her into it.",
                    "question_uk" => "Вона не хотіла відпускати мене, але я зміг умовити її.",
                    "question_ru" => "Она не хотела отпускать меня, но я смог уговорить её.",
                    "answers" => '["skirt around", "back out", "talk"]',
                    "correct_answer" => "talk",
                    "created_at" => now(),
                ],
                [
                    "course_id" => 1,
                    "section_id" => 12,
                    "question" => "To begin with, you must _ up your body.",
                    "question_uk" => "Для початку ти повинен зміцнити тіло.",
                    "question_ru" => "Для начала ты должен укрепить тело.",
                    "answers" => '["weigh up", "yield to", "build"]',
                    "correct_answer" => "build",
                    "created_at" => now(),
                ],
                [
                    "course_id" => 1,
                    "section_id" => 12,
                    "question" => "You've had time to _ over our little tete-a-tete, I hope?",
                    "question_uk" => "Сподіваюся, у вас було час обміркувати нашу розмову тет-а-тет?",
                    "question_ru" => "Надеюсь, у вас было время обдумать наш разговор тет-а-тет?",
                    "answers" => '["hummer out", "make into", "mull"]',
                    "correct_answer" => "mull",
                    "created_at" => now(),
                ],
                [
                    "course_id" => 1,
                    "section_id" => 12,
                    "question" => "Kate _ out at the last minute.",
                    "question_uk" => "Кейт передумала в останню хвилину.",
                    "question_ru" => "Кейт передумала в последнюю минуту.",
                    "answers" => '["held off", "jumped at", "backed"]',
                    "correct_answer" => "backed",
                    "created_at" => now(),
                ],
                [
                    "course_id" => 1,
                    "section_id" => 12,
                    "question" => "I'd _ at the chance to go and live in Japan.",
                    "question_uk" => "Я б використав можливість поїхати і жити в Японії.",
                    "question_ru" => "Я бы использовал возможность поехать и жить в Японии.",
                    "answers" => '["settle on", "rise above", "jump"]',
                    "correct_answer" => "jump",
                    "created_at" => now(),
                ],
                [
                    "course_id" => 1,
                    "section_id" => 13,
                    "question" => "Their last tour _ millions of fans.",
                    "question_uk" => "Їх останнє турне зібрало мільйони шанувальників.",
                    "question_ru" => "Их последнее турне собрало миллионы почитателей.",
                    "answers" => '["got in", "let up", "pulled in"]',
                    "correct_answer" => "pulled in",
                    "created_at" => now(),
                ],
                [
                    "course_id" => 1,
                    "section_id" => 13,
                    "question" => "What time did you _ last night?",
                    "question_uk" => "О котрій годині ви прийшли минулої ночі?",
                    "question_ru" => "В котором часу вы пришли прошлой ночью?",
                    "answers" => '["tear down", "put in", "get in"]',
                    "correct_answer" => "get in",
                    "created_at" => now(),
                ],
                [
                    "course_id" => 1,
                    "section_id" => 13,
                    "question" => "He _ to proposing to her.",
                    "question_uk" => "Він нарешті зробив їй пропозицію.",
                    "question_ru" => "Он наконец сделал ей предложение.",
                    "answers" => '["brought off", "milled around", "got around"]',
                    "correct_answer" => "got around",
                    "created_at" => now(),
                ],
                [
                    "course_id" => 1,
                    "section_id" => 13,
                    "question" => "The arts centre was _ out.",
                    "question_uk" => "Художній центр був заповнений людьми.",
                    "question_ru" => "Художественный центр был заполнен людьми.",
                    "answers" => '["freshened up", "crammed in", "packed out"]',
                    "correct_answer" => "packed out",
                    "created_at" => now(),
                ],
                [
                    "course_id" => 1,
                    "section_id" => 13,
                    "question" => "How did he manage to _ that off?",
                    "question_uk" => "Як йому вдалося з цим впоратися?",
                    "question_ru" => "Как ему удалось успешно с этим справиться?",
                    "answers" => '["bring about", "pull in", "bring off"]',
                    "correct_answer" => "bring off",
                    "created_at" => now(),
                ],
                [
                    "course_id" => 1,
                    "section_id" => 13,
                    "question" => "We plan to _ that old hotel soon.",
                    "question_uk" => "Ми плануємо скоро знести цей старий готель.",
                    "question_ru" => "Мы собираемся скоро снести эту старую гостиницу.",
                    "answers" => '["get around to", "put in", "tear down"]',
                    "correct_answer" => "tear down",
                    "created_at" => now(),
                ],
                [
                    "course_id" => 1,
                    "section_id" => 14,
                    "question" => "In fact, the stock market _ last winter.",
                    "question_uk" => "Фактично фондовий ринок досяг нижньої межі минулої зими.",
                    "question_ru" => "Фактически фондовый рынок достиг нижней границы прошлой зимой.",
                    "answers" => '["stood for", "rolled out", "bottomed out"]',
                    "correct_answer" => "bottomed out",
                    "created_at" => now(),
                ],
                [
                    "course_id" => 1,
                    "section_id" => 14,
                    "question" => "The team _ the project through successfully.",
                    "question_uk" => "Команда успішно завершила проект.",
                    "question_ru" => "Команда успешно завершила проект.",
                    "answers" => '["won back", "set out", "saw"]',
                    "correct_answer" => "saw",
                    "created_at" => now(),
                ],
                [
                    "course_id" => 1,
                    "section_id" => 14,
                    "question" => "I was surprised when the plan _ so easily.",
                    "question_uk" => "Я був здивований, коли план так легко і успішно спрацював.",
                    "question_ru" => "Я был удивлен, когда план так легко и успешно сработал.",
                    "answers" => '["wiped off", "pulled off", "came off"]',
                    "correct_answer" => "came off",
                    "created_at" => now(),
                ],
                [
                    "course_id" => 1,
                    "section_id" => 14,
                    "question" => "The company conducted a survey to _ public opinion.",
                    "question_uk" => "Компанія провела опитування, щоб дізнатися думку громадськості.",
                    "question_ru" => "Компания провела опрос, чтобы узнать мнение народа.",
                    "answers" => '["weed out", "turn out", "sound out"]',
                    "correct_answer" => "sound out",
                    "created_at" => now(),
                ],
                [
                    "course_id" => 1,
                    "section_id" => 14,
                    "question" => "I can _ for the accuracy of those figures.",
                    "question_uk" => "Я можу поручитися за точність цих цифр.",
                    "question_ru" => "Я могу поручиться за точность этих цифр.",
                    "answers" => '["stand up for", "provide for", "vouch"]',
                    "correct_answer" => "vouch",
                    "created_at" => now(),
                ],
                [
                    "course_id" => 1,
                    "section_id" => 14,
                    "question" => "The influx of such immigrants gradually began to _.",
                    "question_uk" => "Приплив таких іммігрантів почав поступово вичерпуватися.",
                    "question_ru" => "Приток таких иммигрантов стал постепенно иссякать.",
                    "answers" => '["start up", "put up", "dry up"]',
                    "correct_answer" => "dry up",
                    "created_at" => now(),
                ],
                [
                    "course_id" => 1,
                    "section_id" => 14,
                    "question" => "Player needs to _ through each step.",
                    "question_uk" => "Гравець повинен обдумати кожен крок.",
                    "question_ru" => "Игрок должен обдумать каждый шаг.",
                    "answers" => '["see through", "muddle through", "think"]',
                    "correct_answer" => "think",
                    "created_at" => now(),
                ],
                [
                    "course_id" => 1,
                    "section_id" => 14,
                    "question" => "If we want to get an adequate result, then real demands must be _ forward.",
                    "question_uk" => "Якщо ми хочемо отримати адекватний результат, то необхідно висунути реальні вимоги.",
                    "question_ru" => "Если мы хотим получить адекватный результат, то необходимо выдвинуть реальные требования.",
                    "answers" => '["draw up", "get over", "put"]',
                    "correct_answer" => "put",
                    "created_at" => now(),
                ],
                [
                    "course_id" => 1,
                    "section_id" => 14,
                    "question" => "Because he didn't bother to _ off his fingerprints.",
                    "question_uk" => "Тому що він не потрудився стерти свої відбитки пальців.",
                    "question_ru" => "Потому что он не потрудился стереть свои отпечатки.",
                    "answers" => '["come off", "make for", "wipe"]',
                    "correct_answer" => "wipe",
                    "created_at" => now(),
                ],
                [
                    "course_id" => 1,
                    "section_id" => 14,
                    "question" => "It's a challenge! _ out who can pull off the impossible.",
                    "question_uk" => "Це виклик! З'ясувати, хто може здійснити неможливе.",
                    "question_ru" => "Это вызов! Выяснить, кто может совершить невозможное.",
                    "answers" => '["put into", "wipe off", "figure"]',
                    "correct_answer" => "figure",
                    "created_at" => now(),
                ],
                [
                    "course_id" => 1,
                    "section_id" => 15,
                    "question" => "He's _ his tires.",
                    "question_uk" => "Він накачує шини.",
                    "question_ru" => "Он накачивает шины.",
                    "answers" => '["charging up", "loading up", "pumping up"]',
                    "correct_answer" => "pumping up",
                    "created_at" => now(),
                ],
                [
                    "course_id" => 1,
                    "section_id" => 15,
                    "question" => "Do you think someone is _ on our conversation?",
                    "question_uk" => "Як думаєш, хтось підслуховує нашу розмову?",
                    "question_ru" => "Как думаешь, кто-то подслушивает наш разговор?",
                    "answers" => '["measuring out", "plugging into", "listening in"]',
                    "correct_answer" => "listening in",
                    "created_at" => now(),
                ],
                [
                    "course_id" => 1,
                    "section_id" => 15,
                    "question" => "Emma is _ the washing machine.",
                    "question_uk" => "Емма завантажує пральну машину.",
                    "question_ru" => "Эмма загружает стиральную машину.",
                    "answers" => '["logging up", "hacking into", "loading up"]',
                    "correct_answer" => "loading up",
                    "created_at" => now(),
                ],
                [
                    "course_id" => 1,
                    "section_id" => 15,
                    "question" => "Someone _ the computers at work.",
                    "question_uk" => "Хтось зламав комп'ютери на роботі.",
                    "question_ru" => "Кто-то сломал компьютеры на работе.",
                    "answers" => '["logged out", "pumped up", "hacked into"]',
                    "correct_answer" => "hacked into",
                    "created_at" => now(),
                ],
                [
                    "course_id" => 1,
                    "section_id" => 16,
                    "question" => "I hate being _ for time.",
                    "question_uk" => "Я ненавиджу бути обмеженим у часі.",
                    "question_ru" => "Я ненавижу быть ограниченным во времени.",
                    "answers" => '["bringing forward", "dragging on", "pressed"]',
                    "correct_answer" => "pressed",
                    "created_at" => now(),
                ],
                [
                    "course_id" => 1,
                    "section_id" => 16,
                    "question" => "You know what, sweetie _.",
                    "question_uk" => "Знаєш що, люба, зачекай.",
                    "question_ru" => "Знаешь что, милая, подожди.",
                    "answers" => '["lie ahead", "pass by", "hang on"]',
                    "correct_answer" => "hang on",
                    "created_at" => now(),
                ],
                [
                    "course_id" => 1,
                    "section_id" => 16,
                    "question" => "We do know that troubles _ ahead.",
                    "question_uk" => "Ми знаємо, що попереду нас чекають труднощі.",
                    "question_ru" => "Мы знаем, что впереди нас ждут трудности.",
                    "answers" => '["hang on", "date back", "lie"]',
                    "correct_answer" => "lie",
                    "created_at" => now(),
                ],
                [
                    "course_id" => 1,
                    "section_id" => 16,
                    "question" => "I've heard he will surely _ this way.",
                    "question_uk" => "Я чула, що він обов'язково тут пройде.",
                    "question_ru" => "Я слышала, что он обязательно здесь будет проходить.",
                    "answers" => '["knock about", "drag on", "pass by"]',
                    "correct_answer" => "pass by",
                    "created_at" => now(),
                ],
                [
                    "course_id" => 1,
                    "section_id" => 17,
                    "question" => "All the profits are being _ back into the company.",
                    "question_uk" => "Вся прибуток вкладається в компанію.",
                    "question_ru" => "Вся прибыль вкладывается в компанию.",
                    "answers" => '["put by", "bailed out", "ploughed"]',
                    "correct_answer" => "ploughed",
                    "created_at" => now(),
                ],
                [
                    "course_id" => 1,
                    "section_id" => 17,
                    "question" => "I try to _ a few pounds every week.",
                    "question_uk" => "Я стараюся відкладати кілька фунтів щотижня.",
                    "question_ru" => "Я стараюсь откладывать несколько фунтов каждую неделю.",
                    "answers" => '["work off", "pay in", "put by"]',
                    "correct_answer" => "put by",
                    "created_at" => now(),
                ],
                [
                    "course_id" => 1,
                    "section_id" => 17,
                    "question" => "I _ through a huge amount of money last week.",
                    "question_uk" => "Я витратив величезну кількість грошей минулого тижня.",
                    "question_ru" => "Я потратил огромное количество денег на прошлой неделе.",
                    "answers" => '["squared up", "puzzled out", "ran"]',
                    "correct_answer" => "ran",
                    "created_at" => now(),
                ],
                [
                    "course_id" => 1,
                    "section_id" => 17,
                    "question" => "If you pay for both tickets now, I'll _ with you later.",
                    "question_uk" => "Якщо ти зараз заплатиш за обидва квитки, то я поверну тобі гроші з часом.",
                    "question_ru" => "Если ты сейчас заплатишь за оба билета, то я верну тебе деньги со временем.",
                    "answers" => '["run through", "pay back", "square up"]',
                    "correct_answer" => "square up",
                    "created_at" => now(),
                ],
                [
                    "course_id" => 1,
                    "section_id" => 17,
                    "question" => "They are told they must _ their debt.",
                    "question_uk" => "Їм кажуть, що вони повинні відпрацювати свій борг.",
                    "question_ru" => "Им говорят что должны отработать свой долг.",
                    "answers" => '["empty out", "plough back", "work off"]',
                    "correct_answer" => "work off",
                    "created_at" => now(),
                ],
                [
                    "course_id" => 1,
                    "section_id" => 18,
                    "question" => "Maybe it'll _ over.",
                    "question_uk" => "Можливо, все затихне.",
                    "question_ru" => "Может все затихнет.",
                    "answers" => '["come out", "get behind", "blow"]',
                    "correct_answer" => "blow",
                    "created_at" => now(),
                ],
                [
                    "course_id" => 1,
                    "section_id" => 18,
                    "question" => "He's always _ himself down.",
                    "question_uk" => "Він завжди себе критикує.",
                    "question_ru" => "Он всегда себя критикует.",
                    "answers" => '["shutting up", "catching up with", "running"]',
                    "correct_answer" => "running",
                    "created_at" => now(),
                ],
                [
                    "course_id" => 1,
                    "section_id" => 18,
                    "question" => "It was not clear if police would choose to _ down.",
                    "question_uk" => "Було неясно, чи стане поліція вживати жорстоких заходів.",
                    "question_ru" => "Было неясно, станет ли полиция предпринимать жестокие меры.",
                    "answers" => '["kick out", "impose on", "crack"]',
                    "correct_answer" => "crack",
                    "created_at" => now(),
                ],
                [
                    "course_id" => 1,
                    "section_id" => 18,
                    "question" => "You have to _ at with many different ways.",
                    "question_uk" => "Ви повинні підійти до цього з різних сторін.",
                    "question_ru" => "Вы должны подойти к этому с разных сторон.",
                    "answers" => '["climb down", "get by", "come"]',
                    "correct_answer" => "come",
                    "created_at" => now(),
                ],
                [
                    "course_id" => 1,
                    "section_id" => 18,
                    "question" => "I knew he could help me _ out the best in myself.",
                    "question_uk" => "Я знав, що він може допомогти мені виявити найкраще в собі.",
                    "question_ru" => "Я знал, что он может помочь мне выявить лучшее в себе.",
                    "answers" => '["give in", "own up", "bring"]',
                    "correct_answer" => "bring",
                    "created_at" => now(),
                ],
                [
                    "course_id" => 1,
                    "section_id" => 18,
                    "question" => "That's what they want to _ on us.",
                    "question_uk" => "Це те, що вони хотіли нам нав'язати.",
                    "question_ru" => "Это то, что хотели нам навязать.",
                    "answers" => '["fall out", "figure out", "impose"]',
                    "correct_answer" => "impose",
                    "created_at" => now(),
                ],
                [
                    "course_id" => 1,
                    "section_id" => 18,
                    "question" => "I know that you took his _ daddy.",
                    "question_uk" => "Я знаю, що ти стала на його бік проти тата.",
                    "question_ru" => "Я знаю, что ты встала на его сторону против папы.",
                    "answers" => '["harp on", "bank on", "side against"]',
                    "correct_answer" => "side against",
                    "created_at" => now(),
                ],
                [
                    "course_id" => 1,
                    "section_id" => 18,
                    "question" => "I have twins in my class I always _ them.",
                    "question_uk" => "У мене в класі є близнюки, я завжди їх плутаю.",
                    "question_ru" => "У меня в классе есть близнецы, я всегда их путаю.",
                    "answers" => '["round on", "break away", "muddle up"]',
                    "correct_answer" => "muddle up",
                    "created_at" => now(),
                ],
                [
                    "course_id" => 1,
                    "section_id" => 18,
                    "question" => "Nobody _ to breaking the window.",
                    "question_uk" => "Ніхто не зізнався, хто розбив вікно.",
                    "question_ru" => "Никто не признавался, кто разбил окно.",
                    "answers" => '["came out", "got down", "owned up"]',
                    "correct_answer" => "owned",
                    "created_at" => now(),
                ],
                [
                    "course_id" => 1,
                    "section_id" => 18,
                    "question" => "Go away and _ alone!",
                    "question_uk" => "Іди звідси і залиш мене одну!",
                    "question_ru" => "Уйди отсюда и оставь меня одну!",
                    "answers" => '["look down on", "break away", "leave me"]',
                    "correct_answer" => "leave",
                    "created_at" => now(),
                ],

            ]);
        }
    }
}


