<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class AddPracticeQuestions extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        {
            DB::table('practice')->insert([


                [
                    'course_id' => 1,
                    'section_id' => 1,
                    'question' => 'Did you _ who took the cookie?',
                    'question_uk' => 'Ти дізнався хто взяв печиво?',
                    'question_ru' => 'Ты узнал кто взял печенье?',
                    'answers' => '["find out", "look up", "figure out"]',
                    'correct_answer' => 'find out',
                    'created_at' => now(),
                    ],
                    [
                    'course_id' => 1,
                    'section_id' => 1,
                    'question' => 'The concert didn’t _ to my expectations.',
                    'question_uk' => 'Концерт не виправдав моїх сподівань.',
                    'question_ru' => 'Концерт не оправдал моих надежд.',
                    'answers' => '["live up", "measure up", "keep up"]',
                    'correct_answer' => 'live up',
                    'created_at' => now(),
                    ],
                    [
                    'course_id' => 1,
                    'section_id' => 1,
                    'question' => 'I’m sorry, but I don’t think he will ever _.',
                    'question_uk' => 'Пробачте, але я не думаю, що він коли-небудь заспокоїться.',
                    'question_ru' => 'Простите, но я не думаю, что он когда-то остепенится.',
                    'answers' => '["settle down", "calm down", "sit down"]',
                    'correct_answer' => 'settle down',
                    'created_at' => now(),
                    ],
                    [
                    'course_id' => 1,
                    'section_id' => 1,
                    'question' => 'I’m cold could you _ the heating _ , please?',
                    'question_uk' => 'Мені холодно, можна, будь ласка, збільшити опалення?',
                    'question_ru' => 'Мне холодно, можно, пожалуйста, увеличить отопление?',
                    'answers' => '["turn up", "turn down", "turn off"]',
                    'correct_answer' => 'turn up',
                    'created_at' => now(),
                    ],
                    [
                    'course_id' => 1,
                    'section_id' => 1,
                    'question' => 'We\'ll give him a couple hours to _ .',
                    'question_uk' => 'Ми дамо йому пару годин, щоб охолонути.',
                    'question_ru' => 'Мы дадим ему пару часов, чтобы охладиться.',
                    'answers' => '["cool off", "cool down", "cool up"]',
                    'correct_answer' => 'cool off',
                    'created_at' => now(),
                    ],
                    [
                    'course_id' => 1,
                    'section_id' => 1,
                    'question' => 'Look _ my brother while I\'m gone.',
                    'question_uk' => 'Доглядай за моїм братом, поки мене нема.',
                    'question_ru' => 'Посмотрите за моим братом, пока меня нет.',
                    'answers' => '["after", "for", "at"]',
                    'correct_answer' => 'after',
                    'created_at' => now(),
                    ],
                    [
                    'course_id' => 1,
                    'section_id' => 1,
                    'question' => 'She thinks you _ about the house.',
                    'question_uk' => 'Вона думає, що ти байдикуєш по дому.',
                    'question_ru' => 'Она думает, что ты бездельничаешь по дому.',
                    'answers' => '["laze about", "wander around", "laze around"]',
                    'correct_answer' => 'laze about',
                    'created_at' => now(),
                    ],
                    [
                    'course_id' => 1,
                    'section_id' => 1,
                    'question' => 'I don’t _ to going out tonight.',
                    'question_uk' => 'Я не в настрої йти кудись сьогодні ввечері.',
                    'question_ru' => 'Я не в настроении, чтобы идти куда-то сегодня вечером.',
                    'answers' => '["feel up", "feel like", "feel"]',
                    'correct_answer' => 'feel up',
                    'created_at' => now(),
                    ],
                    [
                    'course_id' => 1,
                    'section_id' => 1,
                    'question' => 'Let me see if I can _ .',
                    'question_uk' => 'Дай мені подивитися, чи можу я збільшити.',
                    'question_ru' => 'Посмотрим, может удастся увеличить.',
                    'answers' => '["zoom in", "zoom out", "zoom"]',
                    'correct_answer' => 'zoom in',
                    'created_at' => now(),
                    ],
                    [
                    'course_id' => 1,
                    'section_id' => 1,
                    'question' => 'They _ a lot of the scenes with her.',
                    'question_uk' => 'Вони вирізали багато сцен з нею.',
                    'question_ru' => 'Они вырезали большинство сцен с ней.',
                    'answers' => '["cut out", "cut off", "cut down"]',
                    'correct_answer' => 'cut out',
                    'created_at' => now(),
                    ],
                    [
                    'course_id' => 1,
                    'section_id' => 2,
                    'question' => 'She opened the door and _ me _.',
                    'question_uk' => 'Вона відкрила двері і впустила мене.',
                    'question_ru' => 'Она открыла двери и впустила меня.',
                    'answers' => '["let in", "call in", "rub in"]',
                    'correct_answer' => 'let in',
                    'created_at' => now(),
                    ],
                    [
                    'course_id' => 1,
                    'section_id' => 2,
                    'question' => 'Don’t leave them on your desk and let them _.',
                    'question_uk' => 'Не залишайте речі на столі і не дозволяйте їм накопичуватися.',
                    'question_ru' => 'Не оставляйте вещи на столе и не позволяйте им скапливаться.',
                    'answers' => '["pile up", "nod off", "double up"]',
                    'correct_answer' => 'pile up',
                    'created_at' => now(),
                    ],
                    [
                    'course_id' => 1,
                    'section_id' => 2,
                    'question' => 'The shirt really _ his new tie.',
                    'question_uk' => 'Сорочка дійсно підкреслювала його нову краватку.',
                    'question_ru' => 'Сорочка действительно подчеркивала его новый галстук.',
                    'answers' => '["showed off", "looked for", "reached out"]',
                    'correct_answer' => 'showed off',
                    'created_at' => now(),
                    ],
                    [
                    'course_id' => 1,
                    'section_id' => 2,
                    'question' => 'My boots are _ at the seams.',
                    'question_uk' => 'Мої чоботи розходяться по швах.',
                    'question_ru' => 'Мои ботинки расходятся по швам.',
                    'answers' => '["coming apart", "dropping by", "using up"]',
                    'correct_answer' => 'coming apart',
                    'created_at' => now(),
                    ],
                    [
                    'course_id' => 1,
                    'section_id' => 2,
                    'question' => 'When we arrived, her boyfriend _ drinks.',
                    'question_uk' => 'Коли ми прийшли, її хлопець розливав напої.',
                    'question_ru' => 'Когда мы пришли ее парень разливал напитки.',
                    'answers' => '["poured out", "lined up", "put aside"]',
                    'correct_answer' => 'poured out',
                    'created_at' => now(),
                    ],
                    [
                    'course_id' => 1,
                    'section_id' => 2,
                    'question' => 'He _ his jacket.',
                    'question_uk' => 'Він застібнув піджак.',
                    'question_ru' => 'Он застегнул пиджак.',
                    'answers' => '["zipped up", "fixed up", "paid for"]',
                    'correct_answer' => 'zipped up',
                    'created_at' => now(),
                    ],
                    [
                    'course_id' => 1,
                    'section_id' => 2,
                    'question' => 'They managed to _ 47 samples of different ages.',
                    'question_uk' => 'Їм вдалося відкопати 47 зразків різного віку.',
                    'question_ru' => 'Им удалось откопать 47 образцов разного возраста.',
                    'answers' => '["dig out", "double up", "throw out"]',
                    'correct_answer' => 'dig out',
                    'created_at' => now(),
                    ],
                    [
                    'course_id' => 1,
                    'section_id' => 2,
                    'question' => 'After our busy day, we both sat and _ in front of the TV.',
                    'question_uk' => 'Після напруженого дня ми обоє сіли і задрімали перед телевізором.',
                    'question_ru' => 'После напряженного дня мы оба сели и «отключились» перед телевизором.',
                    'answers' => '["nodded off", "joined in", "turned down"]',
                    'correct_answer' => 'nodded off',
                    'created_at' => now(),
                    ],
                    [
                    'course_id' => 1,
                    'section_id' => 2,
                    'question' => 'I’m just starting to _ after taking the dogs out this morning.',
                    'question_uk' => 'Я тільки починаю зігріватися після ранкової прогулянки з собаками.',
                    'question_ru' => 'Я только начинаю согреваться после утренней прогулки с псами.',
                    'answers' => '["throw out", "throw away", "come back"]',
                    'correct_answer' => 'throw out',
                    'created_at' => now(),
                    ],
                    [
                    'course_id' => 1,
                    'section_id' => 2,
                    'question' => 'I _ the dust from my shoes every day.',
                    'question_uk' => 'Я очищаю пил з моїх черевиків кожен день.',
                    'question_ru' => 'Я очищаю пыль с моих ботинок каждый день.',
                    'answers' => '["brush off", "clean up", "rub in"]',
                    'correct_answer' => 'brush off',
                    'created_at' => now(),
                    ],
                    [
                        'course_id' => 1,
                        'section_id' => 3,
                        'question' => 'I\'d like to _ your friend Phoebe.',
                        'question_uk' => 'Я б хотів запросити вашу подругу Фібі.',
                        'question_ru' => 'Я бы хотел пригласить вашу подругу Фиби.',
                        'answers' => '["ask out", "get at", "take over"]',
                        'correct_answer' => 'ask out',
                        'created_at' => now(),
                    ],

                    [
                        'course_id' => 1,
                        'section_id' => 3,
                        'question' => 'He is too smart to _ for that trick.',
                        'question_uk' => 'Він надто розумний, щоб попастися на цей трюк.',
                        'question_ru' => 'Он слишком умный, чтобы вестись на этот трюк.',
                        'answers' => '["fall for", "get around", "go on"]',
                        'correct_answer' => 'fall for',
                        'created_at' => now(),
                    ],

                    [
                        'course_id' => 1,
                        'section_id' => 3,
                        'question' => 'I _ from my cousin.',
                        'question_uk' => 'Я отримав повідомлення від свого двоюрідного брата.',
                        'question_ru' => 'Я получил известие от моего двоюродного брата.',
                        'answers' => '["heard", "dropped around", "write up"]',
                        'correct_answer' => 'heard from',
                        'created_at' => now(),
                    ],

                    [
                        'course_id' => 1,
                        'section_id' => 3,
                        'question' => 'You can always _ Kate!',
                        'question_uk' => 'Ти завжди можеш покластися на Кейт!',
                        'question_ru' => 'Ты всегда можешь положиться на Кейт!',
                        'answers' => '["depend on", "keep off", "speak up"]',
                        'correct_answer' => 'depend on',
                        'created_at' => now(),
                    ],

                    [
                        'course_id' => 1,
                        'section_id' => 3,
                        'question' => 'She _ to a friend that she had lied to her mum.',
                        'question_uk' => 'Вона розповіла другові, що вона обманула маму.',
                        'question_ru' => 'Она рассказала другу, что солгала маме.',
                        'answers' => '["let on", "dried up", "droned on"]',
                        'correct_answer' => 'let on',
                        'created_at' => now(),
                    ],

                    [
                        'course_id' => 1,
                        'section_id' => 3,
                        'question' => '_ the book _ to Michael, please.',
                        'question_uk' => 'Передайте книгу Майклу, будь ласка.',
                        'question_ru' => 'Передай книгу Майклу, пожалуйста.',
                        'answers' => '["pass on", "leave aside", "open up"]',
                        'correct_answer' => 'pass on',
                        'created_at' => now(),
                    ],

                    [
                        'course_id' => 1,
                        'section_id' => 3,
                        'question' => 'I have to _ the confession _ of him.',
                        'question_uk' => 'Я повинна вибити з нього визнання.',
                        'question_ru' => 'Я должна вытянуть признание из него.',
                        'answers' => '["drag out", "break in", "get through"]',
                        'correct_answer' => 'drag out',
                        'created_at' => now(),
                    ],

                    [
                        'course_id' => 1,
                        'section_id' => 3,
                        'question' => 'I’m sorry to _ on your conversation.',
                        'question_uk' => 'Вибачте, що втрутилась у вашу розмову.',
                        'question_ru' => 'Извините, что вклинилась в ваш разговор.',
                        'answers' => '["break in", "engage in", "lead into"]',
                        'correct_answer' => 'break in',
                        'created_at' => now(),
                    ],

                    [
                        'course_id' => 1,
                        'section_id' => 3,
                        'question' => '_ your heart to him.',
                        'question_uk' => 'Відкрий своє серце йому.',
                        'question_ru' => 'Открой свое сердце ему.',
                        'answers' => '["open up", "mix with", "go along with"]',
                        'correct_answer' => 'open up',
                        'created_at' => now(),
                    ],

                    [
                        'course_id' => 1,
                        'section_id' => 3,
                        'question' => 'They just _ my complaints.',
                        'question_uk' => 'Вони просто проігнорували мої скарги.',
                        'question_ru' => 'Они просто проигнорировали мои жалобы.',
                        'answers' => '["brushed aside", "clam up", "take down"]',
                        'correct_answer' => 'brushed aside',
                        'created_at' => now(),
                    ],

                    [
                    'course_id' => 1,
                    'section_id' => 4,
                    'question' => 'How does your husband _ his employees?',
                    'question_uk' => 'Як твій чоловік ладнає зі своїми співробітниками?',
                    'question_ru' => 'Как твой муж ладит со своими сотрудниками?',
                    'answers' => '["get along with", "bring along", "come along"]',
                    'correct_answer' => 'get along with',
                    'created_at' => now(),
                    ],
                    [
                    'course_id' => 1,
                    'section_id' => 4,
                    'question' => 'What do you _ him?',
                    'question_uk' => 'Що ви про нього думаєте?',
                    'question_ru' => 'Что вы о нем думаете?',
                    'answers' => '["make of", "make up", "turn to"]',
                    'correct_answer' => 'make of',
                    'created_at' => now(),
                    ],
                    [
                    'course_id' => 1,
                    'section_id' => 4,
                    'question' => 'I want to _ .',
                    'question_uk' => 'Я хочу наверстати все упущене.',
                    'question_ru' => 'Я хочу наверстать все упущенное.',
                    'answers' => '["catch up", "freeze sb out", "pay back"]',
                    'correct_answer' => 'catch up',
                    'created_at' => now(),

                    'course_id' => 1,
                    'section_id' => 4,
                    'question' => 'I don’t want to _ .',
                    'question_uk' => 'Я не хочу втручатися.',
                    'question_ru' => 'Я не хочу вмешиваться.',
                    'answers' => '["butt in", "pin down", "butter sb up"]',
                    'correct_answer' => 'butt in',
                    'created_at' => now(),
                    ],
                    [
                    'course_id' => 1,
                    'section_id' => 4,
                    'question' => 'Why did this meeting _ ?',
                    'question_uk' => 'Чому відбулася ця зустріч?',
                    'question_ru' => 'Почему произошла эта встреча?',
                    'answers' => '["come about", "get together", "tell apart"]',
                    'correct_answer' => 'come about',
                    'created_at' => now(),
                    ],
                    [
                    'course_id' => 1,
                    'section_id' => 4,
                    'question' => 'Michael _ with Diana at the party yesterday.',
                    'question_uk' => 'Майкл почав зустрічатися з Діаною на вечірці вчора.',
                    'question_ru' => 'Майкл начал встречаться с Дианой вчера на вечеринке.',
                    'answers' => '["paired off", "play at", "clear out"]',
                    'correct_answer' => 'paired off',
                    'created_at' => now(),
                    ],
                    [
                    'course_id' => 1,
                    'section_id' => 4,
                    'question' => 'I think she’s trying to _ her _.',
                    'question_uk' => 'Я думаю, вона намагається задобрити її.',
                    'question_ru' => 'Я думаю она пытается задобрить ее.',
                    'answers' => '["butter up", "finish with sb", "warm to sb"]',
                    'correct_answer' => 'butter up',
                    'created_at' => now(),
                    ],
                    [
                    'course_id' => 1,
                    'section_id' => 4,
                    'question' => 'I always _ those two sisters because they are twins.',
                    'question_uk' => 'Я завжди плутаю цих двох сестер, бо вони близнючки.',
                    'question_ru' => 'Я всегда путаю этих двух сестер, потому что они близнецы.',
                    'answers' => '["mix up", "make up", "bring up"]',
                    'correct_answer' => 'mix up',
                    'created_at' => now(),
                    ],
                    [
                    'course_id' => 1,
                    'section_id' => 4,
                    'question' => 'Why did they _ ?',
                    'question_uk' => 'Чому вони віддалилися один від одного?',
                    'question_ru' => 'Почему они отдалились друг от друга?',
                    'answers' => '["grow apart", "cotton on", "stick up for"]',
                    'correct_answer' => 'grow apart',
                    'created_at' => now(),
                    ],
                    [
                    'course_id' => 1,
                    'section_id' => 4,
                    'question' => 'I think he’s _ me.',
                    'question_uk' => 'Мені здається, він мені зраджує.',
                    'question_ru' => 'Мне кажется он мне изменяет.',
                    'answers' => '["cheating on", "hit it off", "fit in"]',
                    'correct_answer' => 'cheating on',
                    'created_at' => now(),
                    ],
                    [
                    'course_id' => 1,
                    'section_id' => 5,
                    'question' => 'The film _ us _ considerably.',
                    'question_uk' => 'Цей фільм нас дуже розвеселив.',
                    'question_ru' => 'Этот фильм нас очень развеселил.',
                    'answers' => '["cheered up", "grew on sb", "lived for"]',
                    'correct_answer' => 'cheered up',
                    'created_at' => now(),
                    ],
                    [
                    'course_id' => 1,
                    'section_id' => 5,
                    'question' => 'I can’t _ , that you loved me.',
                    'question_uk' => 'Не можу повірити, що ти любила мене.',
                    'question_ru' => 'Не могу поверить, что ты любила меня.',
                    'answers' => '["get over", "gross out", "snake up"]',
                    'correct_answer' => 'get over',
                    'created_at' => now(),
                    ],
                    [
                    'course_id' => 1,
                    'section_id' => 5,
                    'question' => 'He\'s _ to meeting her.',
                    'question_uk' => 'Він з нетерпінням чекає зустрічі з нею.',
                    'question_ru' => 'Он с нетерпением ждет встречи с ней.',
                    'answers' => '["looking forward", "sinking in", "ticking sb on"]',
                    'correct_answer' => 'looking forward',
                    'created_at' => now(),
                    ],
                    [
                    'course_id' => 1,
                    'section_id' => 5,
                    'question' => 'The kids got bored and started _.',
                    'question_uk' => 'Дітям стало нудно і вони почали бешкетувати.',
                    'question_ru' => 'Детям стало скучном и они начали шуметь.',
                    'answers' => '["monkeying around", "warming to", "bowling over"]',
                    'correct_answer' => 'monkeying around',
                    'created_at' => now(),
                    ],
                    [
                    'course_id' => 1,
                    'section_id' => 5,
                    'question' => 'At first she didn’t like the idea, but she _ .',
                    'question_uk' => 'Спочатку їй ця ідея не сподобалася, але вона змінила свою думку.',
                    'question_ru' => 'Сначала ей эта идея не понравилась , но она изменила свое мнение.',
                    'answers' => '["came round", "lighted up", "spilt (sth) out"]',
                    'correct_answer' => 'came round',
                    'created_at' => now(),
                    ],
                    [
                    'course_id' => 1,
                    'section_id' => 5,
                    'question' => 'They _ when they heard what I had done.',
                    'question_uk' => 'Вони раптово розсердилися, коли почули, що я зробив.',
                    'question_ru' => 'Они внезапно рассердились, когда услышали, что я сделал.',
                    'answers' => '["blew up", "cheered up", "chickened out"]',
                    'correct_answer' => 'blew up',
                    'created_at' => now(),
                    ],
                    [
                    'course_id' => 1,
                    'section_id' => 5,
                    'question' => 'The beauty of music _ him _.',
                    'question_uk' => 'Краса музики його захопила.',
                    'question_ru' => 'Красота музыки его захватила.',
                    'answers' => '["carried", "bored into sb", "picked oneself up"]',
                    'correct_answer' => 'carried away',
                    'created_at' => now(),
                    ],
                    [
                    'course_id' => 1,
                    'section_id' => 5,
                    'question' => 'I will not _ .',
                    'question_uk' => 'Я не збираюся здаватися.',
                    'question_ru' => 'Я не собираюсь сдаваться.',
                    'answers' => '["give up", "cut up", "burn out"]',
                    'correct_answer' => 'give up',
                    'created_at' => now(),
                    ],
                    [
                    'course_id' => 1,
                    'section_id' => 5,
                    'question' => 'That song always _ me _ to when I was at university.',
                    'question_uk' => 'Ця пісня нагадує мені про мої студентські роки.',
                    'question_ru' => 'Эта песня напоминает мне о моих студенческих годах.',
                    'answers' => '["takes back", "keeps form", "passes for"]',
                    'correct_answer' => 'takes back',
                    'created_at' => now(),
                    ],
                    [
                    'course_id' => 1,
                    'section_id' => 5,
                    'question' => 'We can\'t let bad memories _ us.',
                    'question_uk' => 'Ми не можемо дозволити поганим спогадам з\'їдати нас.',
                    'question_ru' => 'Мы не можем позволить плохим воспоминаниям съедать нас (изнутри).',
                    'answers' => '["eat away at", "flood back", "tense up"]',
                    'correct_answer' => 'eat away at',
                    'created_at' => now(),
                    ],
                    [
                    'course_id' => 1,
                    'section_id' => 6,
                    'question' => 'The space shuttle will _ at 9 a.m.',
                    'question_uk' => 'Космічний корабель злетить о 9 ранку.',
                    'question_ru' => 'Космический корабль взлетит в 9 утра.',
                    'answers' => '["lift off", "take off", "see off"]',
                    'correct_answer' => 'lift off',
                    'created_at' => now(),
                    ],
                    [
                    'course_id' => 1,
                    'section_id' => 6,
                    'question' => 'We were completely _ from the busy modern world there.',
                    'question_uk' => 'Там ми були повністю відрізані від сучасного світу.',
                    'question_ru' => 'Там мы были полностью отрезаны от мира.',
                    'answers' => '["cut off", "got to", "packed away"]',
                    'correct_answer' => 'cut off',
                    'created_at' => now(),
                    ],
                    [
                    'course_id' => 1,
                    'section_id' => 6,
                    'question' => 'I have to _ and get to work.',
                    'question_uk' => 'Я повинна зареєструватися і приступити до роботи.',
                    'question_ru' => 'Я должна зарегистрироваться и приступить к работе.',
                    'answers' => '["check in", "get into", "eat out"]',
                    'correct_answer' => 'check in',
                    'created_at' => now(),
                    ],
                    [
                    'course_id' => 1,
                    'section_id' => 6,
                    'question' => 'I\'ve been _ on Japan as I\'m going to live there next year.',
                    'question_uk' => 'Я читаю інформацію про Японію, тому що збираюся там жити наступного року.',
                    'question_ru' => 'Я вычитываю информацию о Японии, поскольку собираюсь там жить в следующем году.',
                    'answers' => '["reading up", "making out", "popping in"]',
                    'correct_answer' => 'reading up',
                    'created_at' => now(),
                    ],
                    [
                    'course_id' => 1,
                    'section_id' => 6,
                    'question' => 'When does our train _?',
                    'question_uk' => 'Коли прибуває наш потяг?',
                    'question_ru' => 'Когда прибывает наш поезд?',
                    'answers' => '["get in", "take off", "hop off"]',
                    'correct_answer' => 'get in',
                    'created_at' => now(),
                    ],
                    [
                    'course_id' => 1,
                    'section_id' => 6,
                    'question' => 'We have 15 minutes until our bus, let\'s _ the café and order take away coffee?',
                    'question_uk' => 'У нас 15 хвилин до автобуса, давай зайдемо в кафе і візьмемо каву з собою?',
                    'question_ru' => 'У нас 15 минут до автобуса давай заскочим в кафе и возьмём кофе с собой.',
                    'answers' => '["pop into", "get to", "chill out"]',
                    'correct_answer' => 'pop into',
                    'created_at' => now(),
                    ],
                    [
                    'course_id' => 1,
                    'section_id' => 6,
                    'question' => '_, or we\'ll miss the train.',
                    'question_uk' => 'Поспішай, інакше ми запізнимося на потяг.',
                    'question_ru' => 'Поторопись, иначе мы опоздаем на поезд.',
                    'answers' => '["Hurry up", "lift off", "stop off"]',
                    'correct_answer' => 'Hurry up',
                    'created_at' => now(),
                    ],
                    [
                    'course_id' => 1,
                    'section_id' => 6,
                    'question' => 'I\'d like to travel more, but my salary _ me _.',
                    'question_uk' => 'Я б хотіла більше подорожувати, але моя зарплата мене обмежує.',
                    'question_ru' => 'Я бы хотела больше путешествовать, но моя зарплата меня ограничивает.',
                    'answers' => '["ties down", "brushes up", "tends towards"]',
                    'correct_answer' => 'ties down',
                    'created_at' => now(),
                    ],
                    [
                    'course_id' => 1,
                    'section_id' => 6,
                    'question' => 'The boys _ their tents.',
                    'question_uk' => 'Хлопці спакували свої намети.',
                    'question_ru' => 'Мальчики упаковали свои палатки.',
                    'answers' => '["packed away", "tore off", "winded down"]',
                    'correct_answer' => 'packed away',
                    'created_at' => now(),
                    ],
                    [
                    'course_id' => 1,
                    'section_id' => 6,
                    'question' => 'He _ that he had visited Berlin.',
                    'question_uk' => 'Він вигадав, що був у Берліні.',
                    'question_ru' => 'Он выдумал, что был в Берлине.',
                    'answers' => '["made out", "hurried up", "showed sb around"]',
                    'correct_answer' => 'made out',
                    'created_at' => now(),
                    ],
                    [
                            'course_id' => 1,
                            'section_id' => 7,
                            'question' => 'I think, I\'m _ with the flu.',
                            'question_uk' => 'Мабуть, я захворів на грип.',
                            'question_ru' => 'Кажется я подхватил грипп.',
                            'answers' => '["coming down", "staying up", "fighting off"]',
                            'correct_answer' => 'coming down',
                            'created_at' => now(),
                        ],
                        [
                            'course_id' => 1,
                            'section_id' => 7,
                            'question' => 'She _ and hurt her knee badly.',
                            'question_uk' => 'Вона впала і сильно вдарила коліно.',
                            'question_ru' => 'Онa упала и сильно ударила колено.',
                            'answers' => '["fell over", "flipped out", "pulled through"]',
                            'correct_answer' => 'fell over',
                            'created_at' => now(),
                        ],
                        [
                            'course_id' => 1,
                            'section_id' => 7,
                            'question' => 'I\'m just happy I\'m _ it _.',
                            'question_uk' => 'Я радий, що хоча б стримав блювоту.',
                            'question_ru' => 'Я рад, что хотя бы сдержал рвоту.',
                            'answers' => '["keeping down", "passing out", "keeping away"]',
                            'correct_answer' => 'keeping down',
                            'created_at' => now(),
                        ],
                        [
                            'course_id' => 1,
                            'section_id' => 7,
                            'question' => 'I was hit on the head and _ .',
                            'question_uk' => 'Я отримав удар по голові і втратив свідомість.',
                            'question_ru' => 'Я ударился головой и потерял сознание.',
                            'answers' => '["passed out", "ate away", "brought around"]',
                            'correct_answer' => 'passed out',
                            'created_at' => now(),
                        ],
                        [
                            'course_id' => 1,
                            'section_id' => 7,
                            'question' => 'I\'ve been trying to _ a meeting with my doctor for a week now.',
                            'question_uk' => 'Я вже тиждень намагаюся домовитися про зустріч з лікарем.',
                            'question_ru' => 'Я уже неделю пытаюсь договориться о встрече с доктором.',
                            'answers' => '["fix up", "make out", "wear sb out"]',
                            'correct_answer' => 'fix up',
                            'created_at' => now(),
                        ],
                        [
                            'course_id' => 1,
                            'section_id' => 7,
                            'question' => 'We always do exercises to _ before playing tennis.',
                            'question_uk' => 'Ми завжди розминаємося перед грою в теніс.',
                            'question_ru' => 'Мы всегда разминаемся перед игрой в теннис.',
                            'answers' => '["loosen up", "phase sth out", "frown on"]',
                            'correct_answer' => 'loosen up',
                            'created_at' => now(),
                        ],
                        [
                            'course_id' => 1,
                            'section_id' => 7,
                            'question' => 'Half of Martha\'s class has _ with flu.',
                            'question_uk' => 'Половина класу Марти захворіла на грип.',
                            'question_ru' => 'Половина класса Марты заболела гриппом.',
                            'answers' => '["gone down", "asked after", "dozed off"]',
                            'correct_answer' => 'gone down',
                            'created_at' => now(),
                        ],
                        [
                            'course_id' => 1,
                            'section_id' => 7,
                            'question' => 'When I _ , I want to become a rock star.',
                            'question_uk' => 'Коли я виросту, я хочу стати рок-зіркою.',
                            'question_ru' => 'Когда я вырасту, я хочу стать рок -звездой.',
                            'answers' => '["grow up", "build oneself up", "pull through"]',
                            'correct_answer' => 'grow up',
                            'created_at' => now(),
                        ],
                        [
                            'course_id' => 1,
                            'section_id' => 7,
                            'question' => 'Hey, quit _ ! This is the best part of the film.',
                            'question_uk' => 'Припини дрімати! Це найкраща частина фільму.',
                            'question_ru' => 'Хватить дремать! Это лучшая часть фильма.',
                            'answers' => '["dozing off", "bringing around", "getting up"]',
                            'correct_answer' => 'dozing off',
                            'created_at' => now(),
                        ],
                        [
                            'course_id' => 1,
                            'section_id' => 7,
                            'question' => 'Medicines should always be _ from children.',
                            'question_uk' => 'Ліки завжди слід тримати подалі від дітей.',
                            'question_ru' => 'Лекарства всегда следует держать подальше от детей.',
                            'answers' => '["kept away", "stepped aside", "drank up"]',
                            'correct_answer' => 'kept away',
                            'created_at' => now(),
                        ],
                        [
                            'course_id' => 1,
                            'section_id' => 8,
                            'question' => 'In other words, it could _ .',
                            'question_uk' => 'Іншими словами, це може закінчитися.',
                            'question_ru' => 'Проще говоря он может закончиться.',
                            'answers' => '["run out", "die out", "blow down"]',
                            'correct_answer' => 'run out',
                            'created_at' => now(),
                        ],
                        [
                            'course_id' => 1,
                            'section_id' => 8,
                            'question' => 'A lot of fences _ in the hurricane last night.',
                            'question_uk' => 'Вчорашній ураган знёс багато огорож.',
                            'question_ru' => 'Вчерашний ураган снёс много ограждений.',
                            'answers' => '["blew down", "drew back", "stayed away from"]',
                            'correct_answer' => 'blew down',
                            'created_at' => now(),
                        ],
                        [
                            'course_id' => 1,
                            'section_id' => 8,
                            'question' => 'We _ the main road.',
                            'question_uk' => 'Ми звернули з головної дороги.',
                            'question_ru' => 'Мы свернули с главной дороги.',
                            'answers' => '["turned off", "squashed up", "hung back"]',
                            'correct_answer' => 'turned off',
                            'created_at' => now(),
                        ],
                        [
                            'course_id' => 1,
                            'section_id' => 8,
                            'question' => 'I wasn\'t sure how things would _ at first.',
                            'question_uk' => 'Спочатку я була не впевнена, як все складеться.',
                            'question_ru' => 'Сначала я была неуверенна, как всё сложиться.',
                            'answers' => '["pan out", "hold over", "play along"]',
                            'correct_answer' => 'pan out',
                            'created_at' => now(),
                        ],
                        [
                            'course_id' => 1,
                            'section_id' => 8,
                            'question' => 'The DVD player was _ and eventually broke down.',
                            'question_uk' => 'DVD глючив, а потім зламався.',
                            'question_ru' => 'DVD глючил, а потом сломался.',
                            'answers' => '["playing up", "banging into", "bearing out"]',
                            'correct_answer' => 'playing up',
                            'created_at' => now(),
                        ],
                        [
                            'course_id' => 1,
                            'section_id' => 8,
                            'question' => 'The robber was caught when someone _ the police.',
                            'question_uk' => 'Грабіжника зловили, коли хтось попередив поліцію.',
                            'question_ru' => 'Грабителя поймали, когда кто-то предупредил полицию.',
                            'answers' => '["tipped off", "doomed to", "drew back"]',
                            'correct_answer' => 'tipped off',
                            'created_at' => now(),
                        ],
                        [
                            'course_id' => 1,
                            'section_id' => 8,
                            'question' => 'I heard someone _ my name from a distance.',
                            'question_uk' => 'Я почув, як хтось здалеку викрикнув моє ім\'я.',
                            'question_ru' => 'Я услышал, как кто-то издалека выкрикнул мое имя.',
                            'answers' => '["calling out", "zipping along", "occurring to"]',
                            'correct_answer' => 'calling out',
                            'created_at' => now(),
                        ],
                        [
                            'course_id' => 1,
                            'section_id' => 8,
                            'question' => 'Grandma had to have surgery because her knees _ .',
                            'question_uk' => 'Бабусі довелося робити операцію, тому що її коліна перестали функціонувати.',
                            'question_ru' => 'Бабушке пришлось оперироваться, потому что ее колени перестали функционировать.',
                            'answers' => '["gave out", "swung around", "made into"]',
                            'correct_answer' => 'gave out',
                            'created_at' => now(),
                        ],
                        [
                            'course_id' => 1,
                            'section_id' => 8,
                            'question' => 'I\'m tired - I\'ve been _ all morning.',
                            'question_uk' => 'Я втомився - я бігав весь ранок.',
                            'question_ru' => 'Я устал - я был занят всё утро.',
                            'answers' => '["running around", "going beyond", "calling off"]',
                            'correct_answer' => 'running around',
                            'created_at' => now(),
                        ],
                        [
                            'course_id' => 1,
                            'section_id' => 8,
                            'question' => 'I _ to meet the love of my life.',
                            'question_uk' => 'Мені пощастило зустріти любов всього свого життя.',
                            'question_ru' => 'Мне посчастливилось встретить любовь своей жизни.',
                            'answers' => '["lucked out", "headed off", "running across"]',
                            'correct_answer' => 'lucked out',
                            'created_at' => now(),
                        ],
                          [
                            'course_id' => 1,
                            'section_id' => 9,
                            'question' => 'She _ her mistakes and wrote the correct answers above them.',
                            'question_uk' => 'Вона закреслила свої помилки і написала зверху правильні відповіді.',
                            'question_ru' => 'Она перечеркнула свои ошибки и написала сверху правильные ответы.',
                            'answers' => '["crossed out", "zoned out", "brought up"]',
                            'correct_answer' => 'crossed out',
                            'created_at' => now(),
                        ],
                        [
                            'course_id' => 1,
                            'section_id' => 9,
                            'question' => 'I\'m just _ what you\'ve written.',
                            'question_uk' => 'Я лише швидко переглядаю те, що ви написали.',
                            'question_ru' => 'Я всего лишь быстро просматриваю то, что вы написали.',
                            'answers' => '["looking over", "passing around", "narrowing down"]',
                            'correct_answer' => 'looking over',
                            'created_at' => now(),
                        ],
                        [
                            'course_id' => 1,
                            'section_id' => 9,
                            'question' => 'I totally _ the chemistry exam.',
                            'question_uk' => 'Я повністю провалив тест з хімії.',
                            'question_ru' => 'Я полностью провалил тест по химии.',
                            'answers' => '["screwed up", "plugged away", "rounded off"]',
                            'correct_answer' => 'screwed up',
                            'created_at' => now(),
                        ],
                        [
                            'course_id' => 1,
                            'section_id' => 9,
                            'question' => 'I _ on the last question.',
                            'question_uk' => 'Я зробив помилку на останньому питанні.',
                            'question_ru' => 'Я сделал ошибку в последним вопросе.',
                            'answers' => '["tripped up", "worked at", "tripped up"]',
                            'correct_answer' => 'tripped up',
                            'created_at' => now(),
                        ],
                        [
                            'course_id' => 1,
                            'section_id' => 9,
                            'question' => 'She successfully _ her exams.',
                            'question_uk' => 'Вона успішно здала іспити.',
                            'question_ru' => 'Она успешно сдала экзамены.',
                            'answers' => '["got through", "polished up", "gave back"]',
                            'correct_answer' => 'got through',
                            'created_at' => now(),
                        ],
                        [
                            'course_id' => 1,
                            'section_id' => 9,
                            'question' => 'I know you were trying to _ this morning.',
                            'question_uk' => 'Я знаю, ти намагався вислизнути вранці.',
                            'question_ru' => 'Я знаю, ты пытался ускользнуть утром.',
                            'answers' => '["sneak out", "drop out", "rub up on"]',
                            'correct_answer' => 'sneak out',
                            'created_at' => now(),
                        ],
                        [
                            'course_id' => 1,
                            'section_id' => 9,
                            'question' => 'She _ during the lecture because it was so boring.',
                            'question_uk' => 'Вона не концентрувалася на лекції, бо вона була нудною.',
                            'question_ru' => 'Она не концентрировалась на лекции потому что она была скучной.',
                            'answers' => '["zoned out", "read out", "piped down"]',
                            'correct_answer' => 'zoned out',
                            'created_at' => now(),
                        ],
                        [
                            'course_id' => 1,
                            'section_id' => 9,
                            'question' => 'Concentrate on _ your best skills.',
                            'question_uk' => 'Сфокусуйся на покращенні своїх найкращих навичок.',
                            'question_ru' => 'Сфокусируйся на улучшении своих лучших навыков.',
                            'answers' => '["polishing up", "putting together", "sneaking out"]',
                            'correct_answer' => 'polishing up',
                            'created_at' => now(),
                        ],
                        [
                            'course_id' => 1,
                            'section_id' => 9,
                            'question' => 'You managed to _ the presentation quite well.',
                            'question_uk' => 'Вам вдалося дуже непогано провести презентацію.',
                            'question_ru' => 'Вам очень неплохо удалось провести презентацию.',
                            'answers' => '["carry off", "leap out at", "take in"]',
                            'correct_answer' => 'carry off',
                            'created_at' => now(),
                        ],
                        [
                            'course_id' => 1,
                            'section_id' => 9,
                            'question' => 'The teacher _ the hand _.',
                            'question_uk' => 'Вчитель роздав роздруківки.',
                            'question_ru' => 'Учитель раздал распечатки.',
                            'answers' => '["passed out", "set up", "looked up"]',
                            'correct_answer' => 'passed out',
                            'created_at' => now(),
                        ],
                        [
                        'course_id' => 1,
                        'section_id' => 10,
                        'question' => 'Why did electronic gadgets _ so fast?',
                        'question_uk' => 'Чому електронні пристрої так швидко стали популярними?',
                        'question_ru' => 'Почему электронные устройства так быстро стали пулярными.',
                        'answers' => '["catch on", "fall behind", "hurry up"]',
                        'correct_answer' => 'catch on',
                        'created_at' => now(),
                    ],

                    [
                        'course_id' => 1,
                        'section_id' => 10,
                        'question' => 'The runner _ his teammates.',
                        'question_uk' => 'Бігун відставав від своїх товаришів по команді.',
                        'question_ru' => 'Бегун отставал от своих товарищей по команде.',
                        'answers' => '["fell behind", "got around to", "went through"]',
                        'correct_answer' => 'fell behind',
                        'created_at' => now(),
                    ],

                    [
                        'course_id' => 1,
                        'section_id' => 10,
                        'question' => "She's _ for a new bike.",
                        'question_uk' => 'Вона відкладала гроші на новий велосипед.',
                        'question_ru' => 'Она откладывала деньги на новый велосипед.',
                        'answers' => '["saving up", "loosing out", "turning into"]',
                        'correct_answer' => 'saving up',
                        'created_at' => now(),
                    ],

                    [
                        'course_id' => 1,
                        'section_id' => 10,
                        'question' => 'They _ working after dark.',
                        'question_uk' => 'Вони продовжували працювати, коли стемніло.',
                        'question_ru' => 'Они продолжали работать когда стемнело.',
                        'answers' => '["kept on", "saved up", "came across"]',
                        'correct_answer' => 'kept on',
                        'created_at' => now(),
                    ],

                    [
                        'course_id' => 1,
                        'section_id' => 10,
                        'question' => 'He _ the new knowledge.',
                        'question_uk' => 'Він жадно поглинав нові знання.',
                        'question_ru' => 'Он жадно поглощал новые знания.',
                        'answers' => '["ate up", "kept on", "kept up with"]',
                        'correct_answer' => 'ate up',
                        'created_at' => now(),
                    ],

                    [
                        'course_id' => 1,
                        'section_id' => 10,
                        'question' => 'The idea sounded interesting and I decided to _ it.',
                        'question_uk' => 'Ідея звучала цікаво, і я вирішила дізнатися про неї більше.',
                        'question_ru' => 'Идея звучала интересно, и я решила узнать о ней больше.',
                        'answers' => '["follow up", "spread out", "ate up"]',
                        'correct_answer' => 'follow up',
                        'created_at' => now(),
                    ],

                    [
                        'course_id' => 1,
                        'section_id' => 10,
                        'question' => 'This is the message that we want to _ to the public.',
                        'question_uk' => 'Це те повідомлення, яке ми хочемо донести до громадськості.',
                        'question_ru' => 'Это то сообщение, которое мы хотим донести до общественности.',
                        'answers' => '["get across", "think up", "come up with"]',
                        'correct_answer' => 'get across',
                        'created_at' => now(),
                    ],

                    [
                        'course_id' => 1,
                        'section_id' => 10,
                        'question' => 'She finally _ painting the bedroom.',
                        'question_uk' => 'Вона, нарешті, змогла пофарбувати спальню.',
                        'question_ru' => 'Она, наконец, смогла покрасить спальню.',
                        'answers' => '["got around to", "got into", "got across"]',
                        'correct_answer' => 'got around to',
                        'created_at' => now(),
                    ],

                    [
                        'course_id' => 1,
                        'section_id' => 10,
                        'question' => 'I was sick last week, that\'s why I _ on the chance at a new job.',
                        'question_uk' => 'Я хворіла на минулому тижні, тому втратила шанс на нову роботу.',
                        'question_ru' => 'Я болела на прошлой неделе, поэтому потеряла шанс на новую работу.',
                        'answers' => '["lost out", "caught on", "settled into"]',
                        'correct_answer' => 'lost out',
                        'created_at' => now(),
                    ],

                    [
                        'course_id' => 1,
                        'section_id' => 10,
                        'question' => 'It is rather a difficult issue and we decided not to _ with its solution.',
                        'question_uk' => 'Це досить складне питання, і ми вирішили не поспішати з його вирішенням.',
                        'question_ru' => 'Это достаточно сложный вопрос, и мы решили не торопиться с его решением.',
                        'answers' => '["hurry up", "save up", "follow up"]',
                        'correct_answer' => 'hurry up',
                        'created_at' => now(),
                    ],
                    [
                        'course_id' => 1,
                        'section_id' => 11,
                        'question' => 'We _ the car up and changed the tyre.',
                        'question_uk' => 'Ми підняли автомобіль (на домкраті) і замінили шини.',
                        'question_ru' => 'Мы подняли автомобиль (на домкрате) и заменили шины.',
                        'answers' => '["jacked up", "came by", "fell through"]',
                        'correct_answer' => 'jacked up',
                        'created_at' => now(),
                    ],

                    [
                        'course_id' => 1,
                        'section_id' => 11,
                        'question' => 'The nurse _ me _ in a chair.',
                        'question_uk' => 'Медсестра посадила мене на стілець.',
                        'question_ru' => 'Медсестра посадила меня на стул.',
                        'answers' => '["sat down", "counted out", "stood up"]',
                        'correct_answer' => 'sat down',
                        'created_at' => now(),
                    ],

                    [
                        'course_id' => 1,
                        'section_id' => 11,
                        'question' => 'As he got older, he started to _ a little.',
                        'question_uk' => 'З віком він почав трохи знижувати навантаження.',
                        'question_ru' => 'С возрастом он начал немного снижать нагрузку.',
                        'answers' => '["ease up", "see out", "take on"]',
                        'correct_answer' => 'ease up',
                        'created_at' => now(),
                    ],

                    [
                        'course_id' => 1,
                        'section_id' => 11,
                        'question' => 'I was only _ orders.',
                        'question_uk' => 'Я всього лише виконував накази.',
                        'question_ru' => 'Я всего лишь исполнял приказы.',
                        'answers' => '["carrying out", "working on", "selling out"]',
                        'correct_answer' => 'carrying out',
                        'created_at' => now(),
                    ],

                    [
                        'course_id' => 1,
                        'section_id' => 11,
                        'question' => 'They tried to _ us down on the price.',
                        'question_uk' => 'Вони намагалися знизити для нас ціну.',
                        'question_ru' => 'Они пытались торговаться насчет цены.',
                        'answers' => '["beat down", "go about", "get ahead"]',
                        'correct_answer' => 'beat down',
                        'created_at' => now(),
                    ],

                    [
                        'course_id' => 1,
                        'section_id' => 11,
                        'question' => 'I was immediately _ by the manager.',
                        'question_uk' => 'Менеджер одразу покликав мене на приватну розмову.',
                        'question_ru' => 'Менеджер сразу позвал меня на частный разговор.',
                        'answers' => '["taken aside", "factored in", "got in"]',
                        'correct_answer' => 'taken aside',
                        'created_at' => now(),
                    ],

                    [
                        'course_id' => 1,
                        'section_id' => 11,
                        'question' => 'She said that her husband _ marketing.',
                        'question_uk' => 'Вона сказала, що її чоловік працює в сфері маркетингу.',
                        'question_ru' => 'Она сказала, что её муж работает в сфере маркетинга.',
                        'answers' => '["works in", "carries on with", "sees out"]',
                        'correct_answer' => 'works in',
                        'created_at' => now(),
                    ],

                    [
                        'course_id' => 1,
                        'section_id' => 11,
                        'question' => 'Try not to get too _ in the details.',
                        'question_uk' => 'Спробуйте не занурюватися занадто в деталі.',
                        'question_ru' => 'Постарайся не слишком зацикливаться на деталях.',
                        'answers' => '["bogged down", "take on", "move along"]',
                        'correct_answer' => 'bogged down',
                        'created_at' => now(),
                    ],

                    [
                        'course_id' => 1,
                        'section_id' => 11,
                        'question' => 'I would rather _ several small projects.',
                        'question_uk' => 'Я б воліла працювати над кількома маленькими проектами.',
                        'question_ru' => 'Я предпочитаю работать над несколькими маленькими проектами.',
                        'answers' => '["work on", "spin out", "send off"]',
                        'correct_answer' => 'work on',
                        'created_at' => now(),
                    ],

                    [
                        'course_id' => 1,
                        'section_id' => 11,
                        'question' => 'I\'m dying for the weekend - this week has been so hard.',
                        'question_uk' => 'Я дуже сильно чекаю на вихідні - цей тиждень був дуже важким.',
                        'question_ru' => 'Я очень сильно жду выходных - эта неделя была очень тяжелой.',
                        'answers' => '["dying for", "holding on", "doing over"]',
                        'correct_answer' => 'dying for',
                        'created_at' => now(),
                    ],
                    [
                        'course_id' => 1,
                        'section_id' => 12,
                        'question' => 'For my nineteenth birthday, my friends _ and bought me a watch.',
                        'question_uk' => 'На моє 19-річчя мої друзі скинулися і купили мені годинник.',
                        'question_ru' => 'К моему 19-летию мои друзья сбросились и купили мне часы.',
                        'answers' => '["clubbed together", "matched up", "gathered up"]',
                        'correct_answer' => 'clubbed together',
                        'created_at' => now(),
                    ],

                    [
                        'course_id' => 1,
                        'section_id' => 12,
                        'question' => 'They _ the pros and cons carefully.',
                        'question_uk' => 'Перед тим як прийняти рішення, вони ретельно зважили плюси і мінуси.',
                        'question_ru' => 'Перед тем как принять решение, они тщательно взвесили плюсы и минусы.',
                        'answers' => '["weighed up", "sized up", "headed for"]',
                        'correct_answer' => 'weighed up',
                        'created_at' => now(),
                    ],

                    [
                        'course_id' => 1,
                        'section_id' => 12,
                        'question' => 'The UK _ the death penalty in 1965.',
                        'question_uk' => 'В 1965 році Великобританія скасувала смертну кару.',
                        'question_ru' => 'В 1965 г. Соединенное Королевство отменило смертную казнь.',
                        'answers' => '["did away with", "allowed for", "blended in"]',
                        'correct_answer' => 'did away with',
                        'created_at' => now(),
                    ],

                    [
                        'course_id' => 1,
                        'section_id' => 12,
                        'question' => 'You have to learn to _ negative criticism.',
                        'question_uk' => 'Тобі потрібно навчитися не звертати уваги на негативну критику.',
                        'question_ru' => 'Тебе нужно научиться не обращать внимание на негативную критику.',
                        'answers' => '["rise above", "talk into", "throw out"]',
                        'correct_answer' => 'rise above',
                        'created_at' => now(),
                    ],

                    [
                        'course_id' => 1,
                        'section_id' => 12,
                        'question' => 'The proposal to build a new road was _.',
                        'question_uk' => 'Пропозиція побудувати нову дорогу була відхилена.',
                        'question_ru' => 'Предложение о строительстве новой дороги было отклонено.',
                        'answers' => '["voted down", "spaced out", "came round to"]',
                        'correct_answer' => 'voted down',
                        'created_at' => now(),
                    ],

                    [
                        'course_id' => 1,
                        'section_id' => 12,
                        'question' => 'She didn\'t want to let me go, but I finally managed to _ her _ it.',
                        'question_uk' => 'Вона не хотіла відпускати мене, але я все ж зумів її переконати.',
                        'question_ru' => 'Она не хотела отпускать меня, но я смог уговорить её.',
                        'answers' => '["talk into", "skirt around", "back out"]',
                        'correct_answer' => 'talk into',
                        'created_at' => now(),
                    ],

                    [
                        'course_id' => 1,
                        'section_id' => 12,
                        'question' => 'To begin with, you must _ your body.',
                        'question_uk' => 'Для початку тобі потрібно зміцнити своє тіло.',
                        'question_ru' => 'Для начала ты должен укрепить тело.',
                        'answers' => '["build up", "weigh up", "yield to"]',
                        'correct_answer' => 'build up',
                        'created_at' => now(),
                    ],

                    [
                        'course_id' => 1,
                        'section_id' => 12,
                        'question' => 'You\'ve had time to _ our little tete-a-tete, I hope?',
                        'question_uk' => 'Надіюся, у вас був час обдумати нашу розмову тет-а-тет?',
                        'question_ru' => 'Надеюсь, у вас было время обдумать наш разговор тет-а-тет?',
                        'answers' => '["mull over", "hummer out", "make into"]',
                        'correct_answer' => 'mull over',
                        'created_at' => now(),
                    ],

                    [
                        'course_id' => 1,
                        'section_id' => 12,
                        'question' => 'Kate _ at the last minute.',
                        'question_uk' => 'Кейт передумала в останню хвилину.',
                        'question_ru' => 'Кейт передумала в последнюю минуту.',
                        'answers' => '["backed out", "held off", "jumped at"]',
                        'correct_answer' => 'backed out',
                        'created_at' => now(),
                    ],

                    [
                        'course_id' => 1,
                        'section_id' => 12,
                        'question' => 'I\'d _ the chance to go and live in Japan.',
                        'question_uk' => 'Я б із задоволенням скористався можливістю поїхати і жити в Японії.',
                        'question_ru' => 'Я бы использовал возможность поехать и жить в Японии.',
                        'answers' => '["jump at", "settle on", "rise above"]',
                        'correct_answer' => 'jump at',
                        'created_at' => now(),
                    ],
                    [
                        'course_id' => 1,
                        'section_id' => 13,
                        'question' => 'Their last tour _ millions of fans.',
                        'question_uk' => 'Їхнє останнє турне зібрало мільйони шанувальників.',
                        'question_ru' => 'Их последнее турне собрало миллионы почитателей.',
                        'answers' => '["pulled in", "got in", "let up"]',
                        'correct_answer' => 'pulled in',
                        'created_at' => now(),
                    ],

                    [
                        'course_id' => 1,
                        'section_id' => 13,
                        'question' => 'What time did you _ last night?',
                        'question_uk' => 'В який час ти прийшов минулої ночі?',
                        'question_ru' => 'В котором часу вы пришли прошлой ночью?',
                        'answers' => '["get in", "tear down", "put in"]',
                        'correct_answer' => 'get in',
                        'created_at' => now(),
                    ],

                    [
                        'course_id' => 1,
                        'section_id' => 13,
                        'question' => 'He _ proposing to her.',
                        'question_uk' => 'Він нарешті зробив їй пропозицію.',
                        'question_ru' => 'Он наконец сделал ей предложение.',
                        'answers' => '["got around to", "brought off", "milled around"]',
                        'correct_answer' => 'got around to',
                        'created_at' => now(),
                    ],

                    [
                        'course_id' => 1,
                        'section_id' => 13,
                        'question' => 'The arts centre was _.',
                        'question_uk' => 'Художній центр був переповнений людьми.',
                        'question_ru' => 'Художественный центр был заполнен людьми.',
                        'answers' => '["packed out", "freshened up", "crammed in"]',
                        'correct_answer' => 'packed out',
                        'created_at' => now(),
                    ],

                    [
                        'course_id' => 1,
                        'section_id' => 13,
                        'question' => 'How did he manage to _ that off?',
                        'question_uk' => 'Як йому вдалося успішно впоратися з цим?',
                        'question_ru' => 'Как ему удалось успешно с этим справиться?',
                        'answers' => '["bring off", "bring about", "pull in"]',
                        'correct_answer' => 'bring off',
                        'created_at' => now(),
                    ],

                    [
                        'course_id' => 1,
                        'section_id' => 13,
                        'question' => 'We plan to _ that old hotel soon.',
                        'question_uk' => 'Ми плануємо незабаром знести цю стару готель.',
                        'question_ru' => 'Мы собираемся скоро снести эту старую гостиницу.',
                        'answers' => '["tear down", "get around to", "put in"]',
                        'correct_answer' => 'tear down',
                        'created_at' => now(),
                    ],
                    [
                        'course_id' => 1,
                        'section_id' => 14,
                        'question' => 'In fact, the stock market _ last winter.',
                        'question_uk' => 'Фактично фондовий ринок досяг нижньої межі минулої зими.',
                        'question_ru' => 'Фактически фондовый рынок достиг нижней границы прошлой зимой.',
                        'answers' => '["bottomed out", "stood for", "rolled out"]',
                        'correct_answer' => 'bottomed out',
                        'created_at' => now(),
                    ],

                    [
                        'course_id' => 1,
                        'section_id' => 14,
                        'question' => 'The team _ the project _ successfully.',
                        'question_uk' => 'Команда успішно завершила проект.',
                        'question_ru' => 'Команда успешно завершила проект.',
                        'answers' => '["saw through", "won back", "set out"]',
                        'correct_answer' => 'saw through',
                        'created_at' => now(),
                    ],

                    [
                        'course_id' => 1,
                        'section_id' => 14,
                        'question' => 'I was surprised when the plan _ so easily.',
                        'question_uk' => 'Я був здивований, коли план так легко спрацював.',
                        'question_ru' => 'Я был удивлён, когда план так легко и успешно сработал.',
                        'answers' => '["came off", "wiped off", "pulled off"]',
                        'correct_answer' => 'pulled off',
                        'created_at' => now(),
                    ],

                    [
                        'course_id' => 1,
                        'section_id' => 14,
                        'question' => 'The company conducted a survey to _ public opinion.',
                        'question_uk' => 'Компанія провела опитування, щоб дізнатися громадську думку.',
                        'question_ru' => 'Компания провела опрос, чтобы узнать мнение народа.',
                        'answers' => '["sound out", "weed out", "turn out"]',
                        'correct_answer' => 'sound out',
                        'created_at' => now(),
                    ],

                    [
                        'course_id' => 1,
                        'section_id' => 14,
                        'question' => 'I can _ the accuracy of those figures.',
                        'question_uk' => 'Я можу поручитися за точність цих цифр.',
                        'question_ru' => 'Я могу поручиться за точность этих цифр.',
                        'answers' => '["vouch for", "stand up for", "provide for"]',
                        'correct_answer' => 'vouch for',
                        'created_at' => now(),
                    ],

                    [
                        'course_id' => 1,
                        'section_id' => 14,
                        'question' => 'The influx of such immigrants gradually began to _.',
                        'question_uk' => 'Притік таких іммігрантів поступово почав зменшуватись.',
                        'question_ru' => 'Приток таких иммигрантов стал постепенно иссякать.',
                        'answers' => '["dry up", "start up", "put up"]',
                        'correct_answer' => 'dry up',
                        'created_at' => now(),
                    ],

                    [
                        'course_id' => 1,
                        'section_id' => 14,
                        'question' => 'Players need to _ each step.',
                        'question_uk' => 'Гравці повинні продумати кожен крок.',
                        'question_ru' => 'Игроки должны обдумать каждый шаг.',
                        'answers' => '["think through", "see through", "muddle through"]',
                        'correct_answer' => 'think through',
                        'created_at' => now(),
                    ],

                    [
                        'course_id' => 1,
                        'section_id' => 14,
                        'question' => 'If we want to get an adequate result, then real demands must be _.',
                        'question_uk' => 'Якщо ми хочемо отримати адекватний результат, потрібно висунути реальні вимоги.',
                        'question_ru' => 'Если мы хотим получить адекватный результат, то необходимо выдвинуть реальные требования.',
                        'answers' => '["put forward", "draw up", "get over"]',
                        'correct_answer' => 'put forward',
                        'created_at' => now(),
                    ],

                    [
                        'course_id' => 1,
                        'section_id' => 14,
                        'question' => 'Because he didn\'t bother to _ his fingerprints.',
                        'question_uk' => 'Тому що він не потурбувався стерти свої відбитки.',
                        'question_ru' => 'Потому что он не потрудился стереть свои отпечатки.',
                        'answers' => '["wipe off", "come off", "make for"]',
                        'correct_answer' => 'wipe off',
                        'created_at' => now(),
                    ],

                    [
                        'course_id' => 1,
                        'section_id' => 14,
                        'question' => 'It\'s a challenge! Figure out who can _ the impossible.',
                        'question_uk' => 'Це виклик! З’ясуйте, хто може здійснити неможливе.',
                        'question_ru' => 'Это вызов! Выясните, кто может сделать невозможное.',
                        'answers' => '["pull off", "come up with", "settle on"]',
                        'correct_answer' => 'pull off',
                        'created_at' => now(),
                    ],
                    [
                        'course_id' => 1,
                        'section_id' => 15,
                        'question' => 'He\'s _ his tires.',
                        'question_uk' => 'Він накачує шини.',
                        'question_ru' => 'Он накачивает шины.',
                        'answers' => '["pumping up", "charging up", "loading up"]',
                        'correct_answer' => 'pumping up',
                        'created_at' => now(),
                    ],

                    [
                        'course_id' => 1,
                        'section_id' => 15,
                        'question' => 'Do you think someone is _ on our conversation?',
                        'question_uk' => 'Як думаєш, хтось підслуховує нашу розмову?',
                        'question_ru' => 'Как думаешь, кто-то подслушивает наш разговор?',
                        'answers' => '["listening in", "measuring out", "plugging into"]',
                        'correct_answer' => 'listening in',
                        'created_at' => now(),
                    ],

                    [
                        'course_id' => 1,
                        'section_id' => 15,
                        'question' => 'Emma is _ the washing machine.',
                        'question_uk' => 'Емма завантажує пральну машину.',
                        'question_ru' => 'Эмма загружает стиральную машину.',
                        'answers' => '["loading up", "logging up", "hacking into"]',
                        'correct_answer' => 'loading up',
                        'created_at' => now(),
                    ],

                    [
                        'course_id' => 1,
                        'section_id' => 15,
                        'question' => 'Someone _ the computers at work.',
                        'question_uk' => 'Хтось зламав комп\'ютери на роботі.',
                        'question_ru' => 'Кто-то сломал компьютеры на работе.',
                        'answers' => '["hacked into", "logged out", "pumped up"]',
                        'correct_answer' => 'hacked into',
                        'created_at' => now(),
                    ],
                    [
                        'course_id' => 1,
                        'section_id' => 16,
                        'question' => 'I hate _ for time.',
                        'question_uk' => 'Я ненавиджу бути обмеженим у часі.',
                        'question_ru' => 'Я ненавижу быть ограниченным во времени.',
                        'answers' => '["being pressed", "bringing forward", "dragging on"]',
                        'correct_answer' => 'being pressed',
                        'created_at' => now(),
                    ],

                    [
                        'course_id' => 1,
                        'section_id' => 16,
                        'question' => 'You know what, sweetie _.',
                        'question_uk' => 'Знаєш що, мила, чекай.',
                        'question_ru' => 'Знаешь что, милая, подожди.',
                        'answers' => '["hang on", "lie ahead", "pass by"]',
                        'correct_answer' => 'hang on',
                        'created_at' => now(),
                    ],

                    [
                        'course_id' => 1,
                        'section_id' => 16,
                        'question' => 'We do know that troubles _.',
                        'question_uk' => 'Ми знаємо, що впереди нас чекають труднощі.',
                        'question_ru' => 'Мы знаем, что впереди нас ждут трудности.',
                        'answers' => '["lie ahead", "hang on", "date back"]',
                        'correct_answer' => 'lie ahead',
                        'created_at' => now(),
                    ],

                    [
                        'course_id' => 1,
                        'section_id' => 16,
                        'question' => 'I\'ve heard he will surely _ this way.',
                        'question_uk' => 'Я чула, що він обов\'язково буде проходити цим шляхом.',
                        'question_ru' => 'Я слышала, что он обязательно здесь будет проходить.',
                        'answers' => '["pass by", "knock about", "drag on"]',
                        'correct_answer' => 'pass by',
                        'created_at' => now(),
                    ],
                    [
                        'course_id' => 1,
                        'section_id' => 17,
                        'question' => 'All the profits are being _ into the company.',
                        'question_uk' => 'Вся прибуток вкладається в компанію.',
                        'question_ru' => 'Вся прибыль вкладывается в компанию.',
                        'answers' => '["ploughed back", "put by", "bailed out"]',
                        'correct_answer' => 'ploughed back',
                        'created_at' => now(),
                    ],

                    [
                        'course_id' => 1,
                        'section_id' => 17,
                        'question' => 'I try to _ a few pounds every week.',
                        'question_uk' => 'Я намагаюся відкладати кілька фунтів щотижня.',
                        'question_ru' => 'Я стараюсь откладывать несколько фунтов каждую неделю.',
                        'answers' => '["put by", "work off", "pay in"]',
                        'correct_answer' => 'put by',
                        'created_at' => now(),
                    ],

                    [
                        'course_id' => 1,
                        'section_id' => 17,
                        'question' => 'I _ a huge amount of money last week.',
                        'question_uk' => 'Я витратив величезну суму грошей минулого тижня.',
                        'question_ru' => 'Я потратил огромное количество денег на прошлой неделе.',
                        'answers' => '["ran through", "squared up", "puzzled out"]',
                        'correct_answer' => 'ran through',
                        'created_at' => now(),
                    ],

                    [
                        'course_id' => 1,
                        'section_id' => 17,
                        'question' => 'If you pay for both tickets now, I\'ll _ with you later.',
                        'question_uk' => 'Якщо ти зараз заплатиш за обидва квитка, я поверну тобі гроші пізніше.',
                        'question_ru' => 'Если ты сейчас заплатишь за оба билета, то я верну тебе деньги со временем.',
                        'answers' => '["square up", "run through", "pay back"]',
                        'correct_answer' => 'pay back',
                        'created_at' => now(),
                    ],

                    [
                        'course_id' => 1,
                        'section_id' => 17,
                        'question' => 'They are told they must _ their debt.',
                        'question_uk' => 'Їм кажуть, що вони повинні відпрацювати свій борг.',
                        'question_ru' => 'Им говорят, что они должны отработать свой долг.',
                        'answers' => '["work off", "empty out", "plough back"]',
                        'correct_answer' => 'work off',
                        'created_at' => now(),
                    ],
                    [
                        'course_id' => 1,
                        'section_id' => 18,
                        'question' => 'I could never _ my kid like that.',
                        'question_uk' => 'Я б ніколи не сварила так своїх дітей.',
                        'question_ru' => 'Я бы никогда не ругал так своих детей.',
                        'answers' => '["bawl out", "get by", "shut up"]',
                        'correct_answer' => 'bawl out',
                        'created_at' => now(),
                    ],

                    [
                        'course_id' => 1,
                        'section_id' => 18,
                        'question' => 'Make sure you don\'t _ in your bills.',
                        'question_uk' => 'Переконайтеся, що ви не пропустили оплату рахунків.',
                        'question_ru' => 'Убедитесь, что вы не просрочили оплату счетов.',
                        'answers' => '["get behind", "look down", "bring in"]',
                        'correct_answer' => 'get behind',
                        'created_at' => now(),
                    ],

                    [
                        'course_id' => 1,
                        'section_id' => 18,
                        'question' => 'You shouldn\'t _ those who are less fortunate than you are.',
                        'question_uk' => 'Ти не повинен дивитися на тих, кому повезло менше, ніж тобі.',
                        'question_ru' => 'Ты не должен смотреть свысока на тех, кому повезло меньше, чем тебе.',
                        'answers' => '["look down on", "shut up", "work out"]',
                        'correct_answer' => 'look down on',
                        'created_at' => now(),
                    ],

                    [
                        'course_id' => 1,
                        'section_id' => 18,
                        'question' => 'I think you should _.',
                        'question_uk' => 'Я думаю, тобі слід замовкнути.',
                        'question_ru' => 'Я думаю, тебе следует закрыть рот.',
                        'answers' => '["shut up", "give in", "get by"]',
                        'correct_answer' => 'shut up',
                        'created_at' => now(),
                    ],

                    [
                        'course_id' => 1,
                        'section_id' => 18,
                        'question' => 'Don\'t worry - everything will _ in the end.',
                        'question_uk' => 'Не хвилюйся - все уладиться в кінці.',
                        'question_ru' => 'Не волнуйся - всё уладится в конце концов.',
                        'answers' => '["work out", "bring in", "come out"]',
                        'correct_answer' => 'work out',
                        'created_at' => now(),
                    ],

                    [
                        'course_id' => 1,
                        'section_id' => 18,
                        'question' => 'My husband thinks I can _ without a housekeeper.',
                        'question_uk' => 'Мій чоловік вважає, що я впораюся без домогосподарки.',
                        'question_ru' => 'Мой муж считает, что я справлюсь без помощницы по дому.',
                        'answers' => '["get by", "bawl out", "shut up"]',
                        'correct_answer' => 'get by',
                        'created_at' => now(),
                    ],

                    [
                        'course_id' => 1,
                        'section_id' => 18,
                        'question' => 'It’s obvious that it\'s very difficult to _ her.',
                        'question_uk' => 'Очевидно, її дуже важко переубедити.',
                        'question_ru' => 'Очевидно, её очень тяжело переубедить.',
                        'answers' => '["reason with", "look down on", "bring in"]',
                        'correct_answer' => 'reason with',
                        'created_at' => now(),
                    ],

                    [
                        'course_id' => 1,
                        'section_id' => 18,
                        'question' => 'Don\'t _ anything new!',
                        'question_uk' => 'Не впроваджуйте нічого нового!',
                        'question_ru' => 'Не внедряйте ничего нового!',
                        'answers' => '["bring in", "shut up", "work out"]',
                        'correct_answer' => 'bring in',
                        'created_at' => now(),
                    ],

                    [
                        'course_id' => 1,
                        'section_id' => 18,
                        'question' => 'But the facts will _ at some point.',
                        'question_uk' => 'Але факти з\'являться в будь-який момент.',
                        'question_ru' => 'Однако факты появятся в любой момент.',
                        'answers' => '["come out", "bring in", "bawl out"]',
                        'correct_answer' => 'come out',
                        'created_at' => now(),
                    ],

                    [
                        'course_id' => 1,
                        'section_id' => 18,
                        'question' => 'After one month, the workers had to _.',
                        'question_uk' => 'Через місяць робітники були змушені здатися.',
                        'question_ru' => 'Через месяц рабочие вынуждены были уступить.',
                        'answers' => '["give in", "shut up", "get by"]',
                        'correct_answer' => 'give in',
                        'created_at' => now(),
                    ],
                    [
                        'course_id' => 1,
                        'section_id' => 19,
                        'question' => 'The boxer can _ a wrestler in one blow.',
                        'question_uk' => 'Його боксер може вибити борця одним ударом.',
                        'question_ru' => 'Его боксер может вырубить бойца одним ударом.',
                        'answers' => '["knock out", "break out", "hold out"]',
                        'correct_answer' => 'knock out',
                        'created_at' => now(),
                    ],

                    [
                        'course_id' => 1,
                        'section_id' => 19,
                        'question' => 'They _ the store yesterday.',
                        'question_uk' => 'Вони вчора пограбували магазин.',
                        'question_ru' => 'Они ограбили магазин вчера.',
                        'answers' => '["held up", "made off with", "ran away"]',
                        'correct_answer' => 'held up',
                        'created_at' => now(),
                    ],

                    [
                        'course_id' => 1,
                        'section_id' => 19,
                        'question' => 'What are they _ to?',
                        'question_uk' => 'Що вони задумують?',
                        'question_ru' => 'Что они замышляют?',
                        'answers' => '["getting up to", "cutting off", "closing off"]',
                        'correct_answer' => 'getting up to',
                        'created_at' => now(),
                    ],

                    [
                        'course_id' => 1,
                        'section_id' => 19,
                        'question' => 'He has _ her in the game.',
                        'question_uk' => 'Він поступився їй у грі.',
                        'question_ru' => 'Он уступил ей в игре.',
                        'answers' => '["caved to", "passed away", "botched up"]',
                        'correct_answer' => 'caved to',
                        'created_at' => now(),
                    ],

                    [
                        'course_id' => 1,
                        'section_id' => 19,
                        'question' => 'The governments _ diplomatic relations.',
                        'question_uk' => 'Уряди розірвали дипломатичні відносини.',
                        'question_ru' => 'Правительство разорвало дипломатические отношения.',
                        'answers' => '["broke off", "backed into", "closed off"]',
                        'correct_answer' => 'broke off',
                        'created_at' => now(),
                    ],

                    [
                        'course_id' => 1,
                        'section_id' => 19,
                        'question' => 'You won\'t be _ so lightly by the next time.',
                        'question_uk' => 'Наступного разу тобі це так легко не зійде з рук.',
                        'question_ru' => 'В следующий раз тебе это так легко не сойдёт с рук.',
                        'answers' => '["let off", "lay off", "feel up"]',
                        'correct_answer' => 'let off',
                        'created_at' => now(),
                    ],

                    [
                        'course_id' => 1,
                        'section_id' => 19,
                        'question' => 'The burglars _ through the kitchen window.',
                        'question_uk' => 'Грабіжники вломилися через кухонне вікно.',
                        'question_ru' => 'Грабители вломились через окно на кухне.',
                        'answers' => '["backed in", "cooped up", "held out"]',
                        'correct_answer' => 'backed in',
                        'created_at' => now(),
                    ],

                    [
                        'course_id' => 1,
                        'section_id' => 19,
                        'question' => 'It isn\'t good for you to be _ in the house all day.',
                        'question_uk' => 'Тобі шкідливо залишатися замкненим у домі цілий день.',
                        'question_ru' => 'Вам вредно оставаться закрытым в доме на целый день.',
                        'answers' => '["cooped up", "let off", "screwed up"]',
                        'correct_answer' => 'cooped up',
                        'created_at' => now(),
                    ],

                    [
                        'course_id' => 1,
                        'section_id' => 19,
                        'question' => 'The company _ that financial scandal.',
                        'question_uk' => 'Компанія замовчала про фінансовий скандал.',
                        'question_ru' => 'Компания скрыла финансовый скандал.',
                        'answers' => '["hushed up", "came between", "answered back"]',
                        'correct_answer' => 'hushed up',
                        'created_at' => now(),
                    ],

                    [
                        'course_id' => 1,
                        'section_id' => 19,
                        'question' => 'He _ me but missed.',
                        'question_uk' => 'Він замахнувся на мене, але промахнувся.',
                        'question_ru' => 'Он замахнулся на меня, но промахнулся.',
                        'answers' => '["swung at", "turned on", "kicked out"]',
                        'correct_answer' => 'swung at',
                        'created_at' => now(),
                    ],




            ]);
        }
    }
}


