<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class AddQuizQuestion extends Seeder
{
  public function run(): void
  {
    {
      DB::table('quiz')->insert([
        [
            'course_id' => 1,
            'section_id' => 1,
            'question' => 'Did you find out who took the cookie?',
            'question_uk' => 'Ти дізнався, хто взяв печиво?',
            'question_ru' => 'Ты узнал кто взял печенье?',
            'correct_answer' => 'find out',
            'created_at' => now(),
        ],
        [
            'course_id' => 1,
            'section_id' => 1,
            'question' => 'The concert didn’t live up to my expectations.',
            'question_uk' => 'Концерт не виправдав моїх очікувань.',
            'question_ru' => 'Концерт не оправдал моих надежд.',
            'correct_answer' => 'live up to',
            'created_at' => now(),
        ],
        [
            'course_id' => 1,
            'section_id' => 1,
            'question' => 'I’m sorry, but I don’t think he will ever settle down.',
            'question_uk' => 'Вибачте, але я не думаю, що він коли-небудь оселиться.',
            'question_ru' => 'Простите, но я не думаю, что он когда-то остепенится.',
            'correct_answer' => 'settle down',
            'created_at' => now(),
        ],
        [
            'course_id' => 1,
            'section_id' => 1,
            'question' => 'I’m cold could you turn the heating up, please?',
            'question_uk' => 'Мені холодно, можете, будь ласка, збільшити опалення?',
            'question_ru' => 'Мне холодно, можно, пожалуйста, увеличить отопление?',
            'correct_answer' => 'turn up',
            'created_at' => now(),
        ],
        [
            'course_id' => 1,
            'section_id' => 1,
            'question' => 'We\'ll give him a couple hours to cool off.',
            'question_uk' => 'Ми дамо йому пару годин, щоб охолонути.',
            'question_ru' => 'Мы дадим ему пару часов, чтобы охладиться.',
            'correct_answer' => 'cool off',
            'created_at' => now(),
        ],
        [
            'course_id' => 1,
            'section_id' => 1,
            'question' => 'Look after my brother while I\'m gone.',
            'question_uk' => 'Доглянь за моїм братом, поки мене немає.',
            'question_ru' => 'Посмотрите за моим братом, пока меня нет.',
            'correct_answer' => 'look after',
            'created_at' => now(),
        ],
        [
            'course_id' => 1,
            'section_id' => 1,
            'question' => 'She thinks you laze about the house.',
            'question_uk' => 'Вона думає, що ти байдикуєш вдома.',
            'question_ru' => 'Она думает, что ты бездельничаешь по дому.',
            'correct_answer' => 'laze about',
            'created_at' => now(),
        ],
        [
            'course_id' => 1,
            'section_id' => 1,
            'question' => 'I don’t feel up to going out tonight.',
            'question_uk' => 'Я не в настрої виходити сьогодні ввечері.',
            'question_ru' => 'Я не в настроении, чтобы идти куда-то сегодня вечером.',
            'correct_answer' => 'feel up to',
            'created_at' => now(),
        ],
        [
            'course_id' => 1,
            'section_id' => 1,
            'question' => 'Let me see if I can zoom in.',
            'question_uk' => 'Дозвольте подивитися, чи зможу я збільшити.',
            'question_ru' => 'Посмотрим, может удастся увеличить.',
            'correct_answer' => 'zoom in',
            'created_at' => now(),
        ],
        [
            'course_id' => 1,
            'section_id' => 1,
            'question' => 'They cut out a lot of the scenes with her.',
            'question_uk' => 'Вони вирізали багато сцен з нею.',
            'question_ru' => 'Они вырезали большинство сцен с ней.',
            'correct_answer' => 'cut out',
            'created_at' => now(),
        ],
        [
            'lesson_id' => 1,
            'section_id' => 2,
            'question' => 'You must do up your safety belt in the back of a car.',
            'question_uk' => 'Ви повинні пристібати свій ремінь безпеки на задньому сидінні автомобіля.',
            'question_ru' => 'Вы должны пристегивать свой ремень безопасности на заднем сидении авто.',
            'correct_answer' => 'do up',
            'created_at' => now(),
        ],
        [
            'lesson_id' => 1,
            'section_id' => 2,
            'question' => 'The milk went off because I forgot to put it in the fridge.',
            'question_uk' => 'Молоко зіпсувалося, бо я забув покласти його в холодильник.',
            'question_ru' => 'Молоко испортилось, потому что я забыл положить его в холодильник.',
            'correct_answer' => 'went off',
            'created_at' => now(),
        ],
        [
            'lesson_id' => 1,
            'section_id' => 2,
            'question' => 'I pay for my studies every semester.',
            'question_uk' => 'Я плачу за навчання кожен семестр.',
            'question_ru' => 'Я плачу за учебу каждый семестр.',
            'correct_answer' => 'pay for',
            'created_at' => now(),
        ],
        [
            'lesson_id' => 1,
            'section_id' => 2,
            'question' => 'Try to put aside at least 20 min a day to read a book.',
            'question_uk' => 'Спробуйте виділяти хоча б 20 хвилин на день, щоб почитати книгу.',
            'question_ru' => 'Попробуйте выделять хотя бы 20мин. в день на то, чтобы почитать книгу.',
            'correct_answer' => 'put aside',
            'created_at' => now(),
        ],
        [
            'lesson_id' => 1,
            'section_id' => 2,
            'question' => 'Someone’s used up all the milk.',
            'question_uk' => 'Хтось використав усе молоко.',
            'question_ru' => 'Кто-то использовал все молоко.',
            'correct_answer' => 'used up',
            'created_at' => now(),
        ],
        [
            'lesson_id' => 1,
            'section_id' => 2,
            'question' => 'Drop by and pick up that book.',
            'question_uk' => 'Заїдь і забери ту книгу.',
            'question_ru' => 'Заедь и забери эту книгу.',
            'correct_answer' => 'drop by',
            'created_at' => now(),
        ],
        [
            'lesson_id' => 1,
            'section_id' => 2,
            'question' => 'I’m looking for my keys.',
            'question_uk' => 'Я шукаю свої ключі.',
            'question_ru' => 'Я ищу мои ключи.',
            'correct_answer' => 'looking for',
            'created_at' => now(),
        ],
        [
            'lesson_id' => 1,
            'section_id' => 2,
            'question' => 'There aren’t enough chairs to go around.',
            'question_uk' => 'Тут не вистачає стільців для всіх.',
            'question_ru' => 'Тут не хватает стульев для всех.',
            'correct_answer' => 'go around',
            'created_at' => now(),
        ],
        [
            'lesson_id' => 1,
            'section_id' => 2,
            'question' => 'Now, please fold up your chairs and sweep the floor.',
            'question_uk' => 'Тепер, будь ласка, склади стільці та підмети підлогу.',
            'question_ru' => 'Теперь сложи пожалуйста стулья и подмети пол.',
            'correct_answer' => 'fold up',
            'created_at' => now(),
        ],
        [
            'lesson_id' => 1,
            'section_id' => 2,
            'question' => 'Nick loves fixing up old cars.',
            'question_uk' => 'Нік любить ремонтувати старі автомобілі.',
            'question_ru' => 'Ник любит ремонтировать старые автомобили.',
            'correct_answer' => 'fixing up',
            'created_at' => now(),
        ],
        [
            'lesson_id' => 1,
            'section_id' => 3,
            'question' => 'I’d like to ask out your friend Phoebe.',
            'question_uk' => 'Я б хотів запросити Фібі на побачення.',
            'question_ru' => 'Я бы хотел пригласить Фиби на свидание.',
            'correct_answer' => 'get at, take over',
            'created_at' => now(),
        ],
        [
            'lesson_id' => 1,
            'section_id' => 3,
            'question' => 'He is too smart to fall for that trick.',
            'question_uk' => 'Він занадто розумний, щоб повестися на цей трюк.',
            'question_ru' => 'Он слишком умный, чтобы вестись на этот трюк.',
            'correct_answer' => 'get around, go on',
            'created_at' => now(),
        ],
        [
            'lesson_id' => 1,
            'section_id' => 3,
            'question' => 'I heard from my cousin.',
            'question_uk' => 'Я отримав звістку від мого двоюрідного брата.',
            'question_ru' => 'Я получил известие от моего двоюродного брата.',
            'correct_answer' => 'dropped around, write up',
            'created_at' => now(),
        ],
        [
            'lesson_id' => 1,
            'section_id' => 3,
            'question' => 'You can always depend on Kate!',
            'question_uk' => 'Ти завжди можеш покластися на Кейт!',
            'question_ru' => 'Ты всегда можешь положиться на Кейт!',
            'correct_answer' => 'keep off, speak up',
            'created_at' => now(),
        ],
        [
            'lesson_id' => 1,
            'section_id' => 3,
            'question' => 'She let on to a friend that she had lied to her mum.',
            'question_uk' => 'Вона розповіла другу секрет про те, що вона брехала мамі.',
            'question_ru' => 'Она рассказала другу секрет о том, что она врала маме.',
            'correct_answer' => 'dried up, droned on',
            'created_at' => now(),
        ],
        [
            'lesson_id' => 1,
            'section_id' => 3,
            'question' => 'Pass the book on to Michael, please.',
            'question_uk' => 'Передай книгу Майклу, будь ласка.',
            'question_ru' => 'Передай книгу Майклу, пожалуйста.',
            'correct_answer' => 'leave aside, open up',
            'created_at' => now(),
        ],
        [
            'lesson_id' => 1,
            'section_id' => 3,
            'question' => 'I have to drag the confession out of him.',
            'question_uk' => 'Я повинна витягнути з нього зізнання.',
            'question_ru' => 'Я должна вытянуть (выбить) из него информацию.',
            'correct_answer' => 'break in, get through',
            'created_at' => now(),
        ],
        [
            'lesson_id' => 1,
            'section_id' => 3,
            'question' => 'I’m sorry to break in on your conversation.',
            'question_uk' => 'Вибачте, що втрутилася у вашу розмову.',
            'question_ru' => 'Извините, что вклинилась в ваш разговор.',
            'correct_answer' => 'engage in sb, lead into',
            'created_at' => now(),
        ],
        [
            'lesson_id' => 1,
            'section_id' => 3,
            'question' => 'Open up your heart to him.',
            'question_uk' => 'Відкрий своє серце йому.',
            'question_ru' => 'Раскрой свое сердце ему.',
            'correct_answer' => 'mix with, go along with',
            'created_at' => now(),
        ],
        [
            'lesson_id' => 1,
            'section_id' => 3,
            'question' => 'They just brushed aside my complaints.',
            'question_uk' => 'Вони просто проігнорували мої скарги.',
            'question_ru' => 'Они просто проигнорировали мои жалобы.',
            'correct_answer' => 'clam up, take down',
            'created_at' => now(),
        ],
    ]);
    }
  }
}
