<?php

namespace Database\Seeders;
use Illuminate\Support\Facades\DB;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class Section2PhraseSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('phrases')->insert([
            [
                'course_id' => 1,
                'section_id' => 2,
                'phrase_en' => 'to back onto',
                'phrase_uk' => 'бути повернутим спиною до чогось',
                'phrase_ru' => 'быть повернутым, стоять спиной к чему-то',
                'created_at' => now(),
            ],
            [
                'course_id' => 1,
                'section_id' => 2,
                'phrase_en' => 'to be tucked away',
                'phrase_uk' => 'бути захованим, важко знайти',
                'phrase_ru' => 'быть спрятанным, труднонаходимым',
                'created_at' => now(),
            ],
            [
                'course_id' => 1,
                'section_id' => 2,
                'phrase_en' => 'to call in',
                'phrase_uk' => 'викликати (майстра, робітника тощо)',
                'phrase_ru' => 'вызывать (мастера, рабочего и т.д.)',
                'created_at' => now(),
            ],
            [
                'course_id' => 1,
                'section_id' => 2,
                'phrase_en' => 'to live through',
                'phrase_uk' => 'пережити важку/болісну ситуацію',
                'phrase_ru' => 'пережить тяжелую/болезненную ситуацию',
                'created_at' => now(),
            ],
            [
                'course_id' => 1,
                'section_id' => 2,
                'phrase_en' => 'to clean out',
                'phrase_uk' => 'вичищати, розбирати',
                'phrase_ru' => 'вычищать, разбирать',
                'created_at' => now(),
            ],
            [
                'course_id' => 1,
                'section_id' => 2,
                'phrase_en' => 'to clean up',
                'phrase_uk' => 'наводити порядок, ретельно прибирати',
                'phrase_ru' => 'наводить порядок, тщательно убирать',
                'created_at' => now(),
            ],
            [
                'course_id' => 1,
                'section_id' => 2,
                'phrase_en' => 'to come apart',
                'phrase_uk' => 'розходитися (по швах), розпадатися',
                'phrase_ru' => 'расходиться (по швам), распадаться',
                'created_at' => now(),
            ],
            [
                'course_id' => 1,
                'section_id' => 2,
                'phrase_en' => 'to come back',
                'phrase_uk' => 'повертатися, прийти знову',
                'phrase_ru' => 'возвратиться, придти снова',
                'created_at' => now(),
            ],
            [
                'course_id' => 1,
                'section_id' => 2,
                'phrase_en' => 'to come on',
                'phrase_uk' => 'включатися; починати працювати (про техніку)',
                'phrase_ru' => 'включаться; начинать работать( о технике)',
                'created_at' => now(),
            ],
            // Continue for all other phrases
            [
                'course_id' => 1,
                'section_id' => 2,
                'phrase_en' => 'to do up',
                'phrase_uk' => 'застібати; зав\'язувати',
                'phrase_ru' => 'пристегивать; завязывать',
                'created_at' => now(),
            ],
            [
                'course_id' => 1,
                'section_id' => 2,
                'phrase_en' => 'to do without',
                'phrase_uk' => 'справлятися, обходитися без чогось',
                'phrase_ru' => 'справляться, обходиться без чего-то',
                'created_at' => now(),
            ],
            [
                'course_id' => 1,
                'section_id' => 2,
                'phrase_en' => 'to fix up',
                'phrase_uk' => 'ремонтувати',
                'phrase_ru' => 'ремонтировать',
                'created_at' => now(),
            ],
            [
                'course_id' => 1,
                'section_id' => 2,
                'phrase_en' => 'to go for',
                'phrase_uk' => 'вибирати; прагнути, досягати',
                'phrase_ru' => 'выбирать; стремиться, достигать',
                'created_at' => now(),
            ],
            [
                'course_id' => 1,
                'section_id' => 2,
                'phrase_en' => 'to go off',
                'phrase_uk' => 'псуватися; вимикатися',
                'phrase_ru' => 'портиться; выключаться',
                'created_at' => now(),
            ],
            [
                'course_id' => 1,
                'section_id' => 2,
                'phrase_en' => 'to go together',
                'phrase_uk' => 'поєднуватися; добре виглядати разом',
                'phrase_ru' => 'соединяться; хорошо смотреться вместе',
                'created_at' => now(),
            ],
            [
                'course_id' => 1,
                'section_id' => 2,
                'phrase_en' => 'to go with',
                'phrase_uk' => 'підходити до, приєднуватися до, супроводжувати, піти з',
                'phrase_ru' => 'подходить к, присоединиться к, сопровождать, пойти с',
                'created_at' => now(),
            ],
            [
                'course_id' => 1,
                'section_id' => 2,
                'phrase_en' => 'to jot down',
                'phrase_uk' => 'записувати (швидко)',
                'phrase_ru' => 'записывать (быстро)',
                'created_at' => now(),
            ],
            [
                'course_id' => 1,
                'section_id' => 2,
                'phrase_en' => 'to let in',
                'phrase_uk' => 'впускати, пропускати',
                'phrase_ru' => 'впускать, пропускать',
                'created_at' => now(),
            ],
            [
                'course_id' => 1,
                'section_id' => 2,
                'phrase_en' => 'to line up',
                'phrase_uk' => 'ставити; будувати щось/когось у ряд',
                'phrase_ru' => 'ставить; строить что-то/кого-то в ряд',
                'created_at' => now(),
            ],
            [
                'course_id' => 1,
                'section_id' => 2,
                'phrase_en' => 'to mess up',
                'phrase_uk' => 'створювати безлад, бруднити',
                'phrase_ru' => 'создавать беспорядок, пачкать',
                'created_at' => now(),
            ],
            [
                'course_id' => 1,
                'section_id' => 2,
                'phrase_en' => 'to pay for',
                'phrase_uk' => 'платити за щось',
                'phrase_ru' => 'платить за что-то',
                'created_at' => now(),
            ],
            [
                'course_id' => 1,
                'section_id' => 2,
                'phrase_en' => 'to pay off',
                'phrase_uk' => 'оплачувати борги повністю',
                'phrase_ru' => 'оплачивать долги полностью',
                'created_at' => now(),
            ],
            [
                'course_id' => 1,
                'section_id' => 2,
                'phrase_en' => 'to pick (sb/sth) up',
                'phrase_uk' => 'забирати (когось/щось)',
                'phrase_ru' => 'забирать (кого-то/что-то)',
                'created_at' => now(),
            ],
            [
                'course_id' => 1,
                'section_id' => 2,
                'phrase_en' => 'to pile up',
                'phrase_uk' => 'накопичуватися, збиратися',
                'phrase_ru' => 'накапливаться, собираться',
                'created_at' => now(),
            ],
            [
                'course_id' => 1,
                'section_id' => 2,
                'phrase_en' => 'to pull up',
                'phrase_uk' => 'піднімати',
                'phrase_ru' => 'поднимать',
                'created_at' => now(),
            ],
            [
                'course_id' => 1,
                'section_id' => 2,
                'phrase_en' => 'to put aside',
                'phrase_uk' => 'відкладати, виділяти (час, гроші)',
                'phrase_ru' => 'откладывать, выделять (время, деньги)',
                'created_at' => now(),
            ],
            [
                'course_id' => 1,
                'section_id' => 2,
                'phrase_en' => 'to put away',
                'phrase_uk' => 'класти назад на своє місце',
                'phrase_ru' => 'класть обратно на свое место',
                'created_at' => now(),
            ],
            [
                'course_id' => 1,
                'section_id' => 2,
                'phrase_en' => 'to put out',
                'phrase_uk' => 'гасити, тушити, припиняти горіння',
                'phrase_ru' => 'гасить, тушить, прекращать горение',
                'created_at' => now(),
            ],
            [
                'course_id' => 1,
                'section_id' => 2,
                'phrase_en' => 'to rub in',
                'phrase_uk' => 'втирати (крем)',
                'phrase_ru' => 'втирать (крем)',
                'created_at' => now(),
            ],
            [
                'course_id' => 1,
                'section_id' => 2,
                'phrase_en' => 'to see about',
                'phrase_uk' => 'подбати про щось',
                'phrase_ru' => 'позаботиться о чем-то',
                'created_at' => now(),
            ],
            [
                'course_id' => 1,
                'section_id' => 2,
                'phrase_en' => 'to show off',
                'phrase_uk' => 'акцентувати, підкреслювати',
                'phrase_ru' => 'акцентировать, подчеркивать',
                'created_at' => now(),
            ],
            [
                'course_id' => 1,
                'section_id' => 2,
                'phrase_en' => 'to throw away',
                'phrase_uk' => 'викидати',
                'phrase_ru' => 'выбрасывать',
                'created_at' => now(),
            ],
            [
                'course_id' => 1,
                'section_id' => 2,
                'phrase_en' => 'to turn down',
                'phrase_uk' => 'зменшувати (звук, температуру)',
                'phrase_ru' => 'уменьшать (звук, температуру)',
                'created_at' => now(),
            ],
            [
                'course_id' => 1,
                'section_id' => 2,
                'phrase_en' => 'to use up',
                'phrase_uk' => 'витрачати, використовувати',
                'phrase_ru' => 'тратить, использовать',
                'created_at' => now(),
            ],
            [
                'course_id' => 1,
                'section_id' => 2,
                'phrase_en' => 'to warm up',
                'phrase_uk' => 'розігрівати готову їжу',
                'phrase_ru' => 'разогревать готовую пищу',
                'created_at' => now(),
            ],
            [
                'course_id' => 1,
                'section_id' => 2,
                'phrase_en' => 'to zip up',
                'phrase_uk' => 'застібати блискавку',
                'phrase_ru' => 'застегивать молнию',
                'created_at' => now(),
            ],
            [
                'course_id' => 1,
                'section_id' => 2,
                'phrase_en' => 'to boil over',
                'phrase_uk' => 'перекипіти',
                'phrase_ru' => 'перекипеть «сбежать»',
                'created_at' => now(),
            ],
            [
                'course_id' => 1,
                'section_id' => 2,
                'phrase_en' => 'to chop down',
                'phrase_uk' => 'зрубати дерево',
                'phrase_ru' => 'срубить дерево',
                'created_at' => now(),
            ],
            [
                'course_id' => 1,
                'section_id' => 2,
                'phrase_en' => 'to join in',
                'phrase_uk' => 'приєднатися',
                'phrase_ru' => 'присоединиться',
                'created_at' => now(),
            ],
            [
                'course_id' => 1,
                'section_id' => 2,
                'phrase_en' => 'to live off',
                'phrase_uk' => 'жити на, жити за рахунок',
                'phrase_ru' => 'жить на, жить за счет',
                'created_at' => now(),
            ],
            [
                'course_id' => 1,
                'section_id' => 2,
                'phrase_en' => 'to look for',
                'phrase_uk' => 'шукати',
                'phrase_ru' => 'искать',
                'created_at' => now(),
            ],
            [
                'course_id' => 1,
                'section_id' => 2,
                'phrase_en' => 'to mess around',
                'phrase_uk' => 'возитися, дуріти',
                'phrase_ru' => 'возиться, валять дурака',
                'created_at' => now(),
            ],
            [
                'course_id' => 1,
                'section_id' => 2,
                'phrase_en' => 'to name sb/sth after sb/sth',
                'phrase_uk' => 'називати когось на честь когось',
                'phrase_ru' => 'называть кого-то в честь кого-то',
                'created_at' => now(),
            ],
            [
                'course_id' => 1,
                'section_id' => 2,
                'phrase_en' => 'to pour out sth',
                'phrase_uk' => 'розливати (напої)',
                'phrase_ru' => 'разливать (напитки)',
                'created_at' => now(),
            ],
            [
                'course_id' => 1,
                'section_id' => 2,
                'phrase_en' => 'to reach out',
                'phrase_uk' => 'підтягнутися за чимось',
                'phrase_ru' => 'подтянуться за чем-то',
                'created_at' => now(),
            ],
            [
                'course_id' => 1,
                'section_id' => 2,
                'phrase_en' => 'to add up to sb',
                'phrase_uk' => 'зводитися до',
                'phrase_ru' => 'сводиться к',
                'created_at' => now(),
            ],
            [
                'course_id' => 1,
                'section_id' => 2,
                'phrase_en' => 'to brush sth off',
                'phrase_uk' => 'очищати щось',
                'phrase_ru' => 'отчищать что-то',
                'created_at' => now(),
            ],
            [
                'course_id' => 1,
                'section_id' => 2,
                'phrase_en' => 'to call (in) on sb',
                'phrase_uk' => 'відвідати, завітати (попутно кудись)',
                'phrase_ru' => 'посетить, наведаться (дорогой куда-то)',
                'created_at' => now(),
            ],
            [
                'course_id' => 1,
                'section_id' => 2,
                'phrase_en' => 'to clutter sth up',
                'phrase_uk' => 'захаращувати, засмічувати',
                'phrase_ru' => 'загромождать, засорять',
                'created_at' => now(),
            ],
            [
                'course_id' => 1,
                'section_id' => 2,
                'phrase_en' => 'to curl up',
                'phrase_uk' => 'скрутитися в клубок',
                'phrase_ru' => 'скрутиться в клубок',
                'created_at' => now(),
            ],
            [
                'course_id' => 1,
                'section_id' => 2,
                'phrase_en' => 'to dig out',
                'phrase_uk' => 'знаходити, «відкопувати» (інформацію, речі)',
                'phrase_ru' => 'находить, «откапывать» (информацию, вещи)',
                'created_at' => now(),
            ],
            [
                'course_id' => 1,
                'section_id' => 2,
                'phrase_en' => 'to double up',
                'phrase_uk' => 'ділити (з кимось/щось)',
                'phrase_ru' => 'делить (с кем-то/что-то)',
                'created_at' => now(),
            ],
            [
                'course_id' => 1,
                'section_id' => 2,
                'phrase_en' => 'to drop by',
                'phrase_uk' => 'заїхати (ненадовго і без попередження)',
                'phrase_ru' => 'заехать (ненадолго и без предупреждения)',
                'created_at' => now(),
            ],
            [
                'course_id' => 1,
                'section_id' => 2,
                'phrase_en' => 'to drown out',
                'phrase_uk' => 'заглушити, перекричати',
                'phrase_ru' => 'заглушить, перекричать',
                'created_at' => now(),
            ],
            [
                'course_id' => 1,
                'section_id' => 2,
                'phrase_en' => 'to fend for oneself',
                'phrase_uk' => 'подбати про себе, постояти за себе',
                'phrase_ru' => 'позаботься о себе, постоять за себя',
                'created_at' => now(),
            ],
            [
                'course_id' => 1,
                'section_id' => 2,
                'phrase_en' => 'to fold/do up',
                'phrase_uk' => 'складати',
                'phrase_ru' => 'складывать',
                'created_at' => now(),
            ],
            [
                'course_id' => 1,
                'section_id' => 2,
                'phrase_en' => 'to give back',
                'phrase_uk' => 'повернути (комусь/щось)',
                'phrase_ru' => 'вернуть (кому-то/что-то)',
                'created_at' => now(),
            ],
            [
                'course_id' => 1,
                'section_id' => 2,
                'phrase_en' => 'to go around',
                'phrase_uk' => 'вистачати чогось для всіх (наприклад: вистачає склянок на всіх)',
                'phrase_ru' => 'хватать чего-то для всех (например: хватает стаканов на всех)',
                'created_at' => now(),
            ],
            [
                'course_id' => 1,
                'section_id' => 2,
                'phrase_en' => 'to gobble down / to wolf down',
                'phrase_uk' => 'пожирати, швидко їсти; заглотити, проковтнути',
                'phrase_ru' => 'пожирать, быстро есть; заглотить, проглотить',
                'created_at' => now(),
            ],
            [
                'course_id' => 1,
                'section_id' => 2,
                'phrase_en' => 'to head for',
                'phrase_uk' => 'слідувати, рухатися до',
                'phrase_ru' => 'следовать, двигаться к',
                'created_at' => now(),
            ],
            [
                'course_id' => 1,
                'section_id' => 2,
                'phrase_en' => 'to hoard away',
                'phrase_uk' => 'накопичувати, запасатися; відкладати (на потім)',
                'phrase_ru' => 'накапливать, запасаться; откладывать (на потом)',
                'created_at' => now(),
            ],
            [
                'course_id' => 1,
                'section_id' => 2,
                'phrase_en' => 'to keep up with sth',
                'phrase_uk' => 'бути в курсі («йти в ногу з»)',
                'phrase_ru' => 'быть в курсе («идти в ногу с»)',
                'created_at' => now(),
            ],
            [
                'course_id' => 1,
                'section_id' => 2,
                'phrase_en' => 'to lock up',
                'phrase_uk' => 'закрити всі двері і вікна перед тим, як покинути будівлю',
                'phrase_ru' => 'закрыть все двери и окна перед тем как покинуть здание',
                'created_at' => now(),
            ],
            [
                'course_id' => 1,
                'section_id' => 2,
                'phrase_en' => 'to nod off',
                'phrase_uk' => 'засинати («відключатися»)',
                'phrase_ru' => 'засыпать («отключаться»)',
                'created_at' => now(),
            ],
            [
                'course_id' => 1,
                'section_id' => 2,
                'phrase_en' => 'to roll about/around',
                'phrase_uk' => 'дуже сильно сміятися, падати від сміху',
                'phrase_ru' => 'очень сильно смеяться, падать от смеха',
                'created_at' => now(),
            ],
            [
                'course_id' => 1,
                'section_id' => 2,
                'phrase_en' => 'to run around',
                'phrase_uk' => 'бути дуже зайнятим, бігати по справах',
                'phrase_ru' => 'быть очень занятым, бегать по делам',
                'created_at' => now(),
            ],
            [
                'course_id' => 1,
                'section_id' => 2,
                'phrase_en' => 'to seize up',
                'phrase_uk' => 'перестати функціонувати/працювати',
                'phrase_ru' => 'перестать функционировать/работать',
                'created_at' => now(),
            ],
            [
                'course_id' => 1,
                'section_id' => 2,
                'phrase_en' => 'to spill over',
                'phrase_uk' => 'проливати, розливати(ся)',
                'phrase_ru' => 'проливать, разливать(ся)',
                'created_at' => now(),
            ],
            [
                'course_id' => 1,
                'section_id' => 2,
                'phrase_en' => 'to throw out',
                'phrase_uk' => 'зігрівати(ся)',
                'phrase_ru' => 'согревать(ся)',
                'created_at' => now(),
            ],
            [
                'course_id' => 1,
                'section_id' => 2,
                'phrase_en' => 'to turn into',
                'phrase_uk' => 'змінитися, перевтілюватися, розвиватися',
                'phrase_ru' => 'измениться, перевоплощаться, развеваться',
                'created_at' => now(),
            ]
        ]);

    }
}
